/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_office_to_pdf_officeToPdf_generation_result$schema$value
const _deepseek_ai_dsh_office_to_pdf_officeToPdf_generation_result$schema = () => (_deepseek_ai_dsh_office_to_pdf_officeToPdf_generation_result$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_0$schema$value
const _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_0$schema = () => (_deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_1$schema$value
const _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_1$schema = () => (_deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_1$schema$value ??= z.string())
let _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_2$schema$value
const _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_2$schema = () => (_deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_2$schema$value ??= z.union([z.literal("foreground"), z.literal("background")]))
let _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_result$schema$value
const _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_result$schema = () => (_deepseek_ai_dsh_office_to_pdf_officeToPdf_render_result$schema$value ??= z.object({
  'missingFonts': z.array(z.string()).readonly(),
  'generation': z.intersection(z.string(), z.unknown()).readonly(),
  'offset': z.number().readonly(),
  'data': z.instanceof(Uint8Array),
  'eof': z.boolean().readonly(),
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
  'bytes': z.number().readonly().optional(),
}))
const $resultSnapshot = (input, path) => {
  if (input === null || typeof input !== 'object' || input instanceof Uint8Array) return input
  const toJSON = input.toJSON
  const value = typeof toJSON === 'function' ? toJSON.call(input, path.at(-1)?.toString() ?? 'value') : input
  if (value === null || typeof value !== 'object' || value instanceof Uint8Array) return value
  if (Array.isArray(value)) {
    const items = []
    for (let index = 0, length = value.length; index < length; index++) items.push(value[index])
    return items
  }
  const fields = {}
  for (const key of Object.keys(value)) {
    const item = key === 'toJSON' && value === input ? toJSON : value[key]
    if (key === 'toJSON' && typeof item === 'function') continue
    Object.defineProperty(fields, key, { value: item, enumerable: true, writable: true, configurable: true })
  }
  return fields
}
const $resultContainer = (input, path, ancestors, project, snapshot) => {
  if (input === null || typeof input !== 'object') return project(input)
  const owner = !ancestors.has(input)
  if (!owner && ancestors.get(input) !== path.length) throw new TypeError('Remote result contains a circular object')
  if (owner) ancestors.set(input, path.length)
  try { return project(snapshot ? $resultSnapshot(input, path) : input) }
  finally { if (owner) ancestors.delete(input) }
}
const $encode1 = (value, writeBytes, path, ancestors) => {
  return value instanceof Uint8Array ? writeBytes(value, path) : value
}
const $encode0 = (value, writeBytes, path, ancestors) => {
  return $resultContainer(value, path, ancestors, value => {
    if (value === null || typeof value !== 'object' || Array.isArray(value) || value instanceof Uint8Array) return value
    if (Object.hasOwn(value, 'data')) value['data'] = $encode1(value['data'], writeBytes, [...path, 'data'], ancestors)
    return value
  }, true)
}

export const TYPERT = {
  package: '@deepseek-ai/dsh-office-to-pdf',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-office-to-pdf#officeToPdf/generation',
      service: 'officeToPdf',
      namespace: 'officeToPdf',
      method: 'generation',
      implementation: 'getGeneration',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-office-to-pdf/types#OfficeToPdfGeneration',
        create: _deepseek_ai_dsh_office_to_pdf_officeToPdf_generation_result$schema,
      },
      sourceLocation: {"file":"packages/document/office-to-pdf/src/index.ts","line":175,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-office-to-pdf#officeToPdf/render',
      service: 'officeToPdf',
      namespace: 'officeToPdf',
      method: 'render',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-office-to-pdf#officeToPdf/render:path',
            create: _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_1$schema,
          },
        },
        {
          name: 'priority',
          wire: 'priority',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-office-to-pdf/types#OfficeToPdfPriority',
            create: _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_parameter_2$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-office-to-pdf/types#RenderedDocumentBytes',
        create: _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_result$schema,
        decode: value => _deepseek_ai_dsh_office_to_pdf_officeToPdf_render_result$schema().parse(value),
        encode: (value, writeBytes) => $encode0(value, writeBytes, [], new Map()),
      },
      sourceLocation: {"file":"packages/document/office-to-pdf/src/index.ts","line":160,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "A provider lifetime owns all converters, queued calls, and temporary files.",
        "summary": "A provider lifetime owns all converters, queued calls, and temporary files.",
        "tags": [],
        "jsDoc": "/** A provider lifetime owns all converters, queued calls, and temporary files. */",
        "key": "officeToPdf",
        "exportName": "OfficeToPdf",
        "members": [
          {
            "kind": "property",
            "name": "generation",
            "signature": "readonly generation: OfficeToPdfGeneration = OfficeToPdfGeneration(randomUUID())",
            "summary": "Changes whenever engine, font, or conversion configuration is replaced.",
            "jsDoc": "/** Changes whenever engine, font, or conversion configuration is replaced. */"
          },
          {
            "kind": "method",
            "name": "convert",
            "signature": "convert(request: OfficeToPdfRequest, signal?: AbortSignal): Promise<OfficeToPdfResult>",
            "summary": "Convert Office bytes without modifying the source or writing Session events.",
            "jsDoc": "/**\n * Convert Office bytes without modifying the source or writing Session events.\n * @param request - authorized metadata and deferred bounded source read.\n * @param signal - caller cancellation; provider disposal also stops active work.\n * @returns caller-owned PDF bytes after conversion and scratch cleanup settle; canceled readers reject independently.\n * @throws {OfficeToPdfError} Invalid input, unusable output, or engine failure; cancellation rejects with its reason.\n */"
          },
          {
            "kind": "method",
            "name": "render",
            "signature": "@Remote async render( workspaceFileScope: WorkspaceFileScope, path: string, priority: OfficeToPdfPriority, signal: AbortSignal, ): Promise<RenderedDocumentBytes>",
            "summary": "Read and convert one Office file using the Session's ordinary filesystem authorization.",
            "jsDoc": "/**\n * Read and convert one Office file using the Session's ordinary filesystem authorization.\n * @param workspaceFileScope - Session header lookup shared with workspaceFiles.\n * @param path - absolute or workspace-relative Office path.\n * @param priority - foreground preview or speculative background work.\n * @param signal - Remote cancellation; disposal also cancels outstanding reads and conversions.\n * @returns complete PDF bytes with original source identity and missing font families.\n */"
          },
          {
            "kind": "method",
            "name": "getGeneration",
            "signature": "@Remote('generation') getGeneration(signal: AbortSignal): OfficeToPdfGeneration",
            "summary": "Read the current rendering generation before reusing a Client PDF.",
            "jsDoc": "/**\n * Read the current rendering generation before reusing a Client PDF.\n * @param signal - Remote caller cancellation.\n * @returns provider lifetime, replaced with rendering, font, or engine configuration.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "OfficeExtension",
            "declaration": "export type OfficeExtension = 'doc' | 'docx' | 'xls' | 'xlsx' | 'ppt' | 'pptx';"
          },
          {
            "name": "OfficeSourceKey",
            "declaration": "export type OfficeSourceKey = Branded<'OfficeSourceKey'>;"
          },
          {
            "name": "OfficeToPdfGeneration",
            "declaration": "export type OfficeToPdfGeneration = Branded<'OfficeToPdfGeneration'>;"
          },
          {
            "name": "OfficeToPdfKey",
            "declaration": "export type OfficeToPdfKey = Branded<'OfficeToPdfKey'>;"
          },
          {
            "name": "OfficeToPdfPriority",
            "declaration": "export type OfficeToPdfPriority = 'foreground' | 'background';"
          },
          {
            "name": "OfficeToPdfRequest",
            "declaration": "export interface OfficeToPdfRequest {\n    readonly extension: OfficeExtension;\n    readonly priority: OfficeToPdfPriority;\n    readonly source: { readonly key: OfficeSourceKey; readonly version: string; readonly bytes?: number; read(signal: AbortSignal, maxBytes: number): Promise<{ readonly bytes: Uint8Array; readonly version: string; }>; };\n}"
          },
          {
            "name": "OfficeToPdfResult",
            "declaration": "export interface OfficeToPdfResult {\n    readonly pdf: Uint8Array;\n    readonly missingFonts: string[];\n    readonly cacheKey: OfficeToPdfKey;\n    readonly generation: OfficeToPdfGeneration;\n}"
          },
          {
            "name": "RenderedDocumentBytes",
            "declaration": "export interface RenderedDocumentBytes extends WorkspaceFileBytes {\n    readonly missingFonts: string[];\n    readonly generation: OfficeToPdfGeneration;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "WorkspaceFileBytes",
            "declaration": "export interface WorkspaceFileBytes<Data extends Uint8Array = Uint8Array> extends WorkspaceFileStat {\n    readonly offset: number;\n    readonly data: Data;\n    readonly eof: boolean;\n}"
          },
          {
            "name": "WorkspaceFileScope",
            "declaration": "export interface WorkspaceFileScope {\n    readonly sessionId: SessionId;\n    readonly workspaceRoot: string;\n}"
          },
          {
            "name": "WorkspaceFileStat",
            "declaration": "export interface WorkspaceFileStat {\n    readonly absolutePath: string;\n    readonly version: string;\n    readonly bytes?: number;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
