/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_host_plugin_inventory_pluginInventory_list_result$schema$value
const _deepseek_ai_dsh_host_plugin_inventory_pluginInventory_list_result$schema = () => (_deepseek_ai_dsh_host_plugin_inventory_pluginInventory_list_result$schema$value ??= z.object({
  'managementAvailable': z.boolean().readonly().optional(),
  'entries': z.array(z.object({
  'entryId': z.intersection(z.string(), z.unknown()).readonly(),
  'moduleName': z.string().readonly(),
  'meta': z.object({
  'title': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'description': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'icon': z.string().readonly().optional(),
  'error': z.string().readonly().optional(),
}).readonly().optional(),
  'enabled': z.boolean().readonly(),
  'fiberPhase': z.union([z.literal(null), z.literal("failed"), z.literal("pending"), z.literal("active"), z.literal("loading"), z.literal("unloading")]).readonly(),
})).readonly(),
  'agentPresets': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly().optional(),
  'isDefault': z.boolean().readonly(),
  'broken': z.string().readonly().optional(),
  'rows': z.array(z.object({
  'entryId': z.union([z.literal(null), z.string()]).readonly(),
  'moduleName': z.string().readonly(),
  'meta': z.object({
  'title': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'description': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'icon': z.string().readonly().optional(),
  'error': z.string().readonly().optional(),
}).readonly().optional(),
  'enabled': z.union([z.literal(false), z.literal(true), z.literal("conditional")]).readonly(),
  'condition': z.string().readonly().optional(),
  'fiberPhase': z.union([z.literal(null), z.literal("failed"), z.literal("pending"), z.literal("active"), z.literal("loading"), z.literal("unloading")]).readonly(),
})).readonly(),
})).readonly().optional(),
}))

export const TYPERT = {
  package: '@deepseek-ai/dsh-host-plugin-inventory',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-host-plugin-inventory#pluginInventory/list',
      service: 'pluginInventory',
      namespace: 'pluginInventory',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-plugin-inventory/types#PluginInventorySnapshot',
        create: _deepseek_ai_dsh_host_plugin_inventory_pluginInventory_list_result$schema,
      },
      sourceLocation: {"file":"packages/host/plugin-inventory/src/index.ts","line":71,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
