/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_command_feedback_sessionFeedback_record_parameter_0$schema$value
const _deepseek_ai_dsh_command_feedback_sessionFeedback_record_parameter_0$schema = () => (_deepseek_ai_dsh_command_feedback_sessionFeedback_record_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly().optional(),
  'category': z.union([z.literal("other"), z.literal("task-result"), z.literal("instruction-following"), z.literal("product-interaction"), z.literal("service-stability"), z.literal("resource-cost"), z.literal("security-privacy-permission")]).readonly().optional(),
}))
let _deepseek_ai_dsh_command_feedback_sessionFeedback_record_result$schema$value
const _deepseek_ai_dsh_command_feedback_sessionFeedback_record_result$schema = () => (_deepseek_ai_dsh_command_feedback_sessionFeedback_record_result$schema$value ??= z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'recorded': z.literal(true).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.literal("session-not-found").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}).readonly(),
})]))

export const TYPERT = {
  package: '@deepseek-ai/dsh-command-feedback',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-command-feedback#sessionFeedback/record',
      service: 'sessionFeedback',
      namespace: 'sessionFeedback',
      method: 'record',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-command-feedback/types#SessionFeedbackRecordRequest',
            create: _deepseek_ai_dsh_command_feedback_sessionFeedback_record_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-command-feedback/types#SessionFeedbackRecordResult',
        create: _deepseek_ai_dsh_command_feedback_sessionFeedback_record_result$schema,
      },
      sourceLocation: {"file":"packages/feedback/command-feedback/src/index.ts","line":102,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host Remote through which a product surface records a Session-level remark.",
        "summary": "Host Remote through which a product surface records a Session-level remark.",
        "tags": [],
        "jsDoc": "/** Host Remote through which a product surface records a Session-level remark. */",
        "key": "sessionFeedback",
        "exportName": "SessionFeedbackService",
        "members": [
          {
            "kind": "method",
            "name": "record",
            "signature": "@Remote('record') record(request: SessionFeedbackRecordRequest): Promise<SessionFeedbackRecordResult>",
            "summary": "Record one remark on a live Session.",
            "jsDoc": "/**\n * Record one remark on a live Session.\n * @param request - target Session plus the optional text and category.\n * @returns the recorded postcondition, or `session-not-found` when no live\n * Session carries the id.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "FeedbackCategory",
            "declaration": "export type FeedbackCategory = 'task-result' | 'instruction-following' | 'product-interaction' | 'service-stability' | 'resource-cost' | 'security-privacy-permission' | 'other';"
          },
          {
            "name": "SessionFeedbackRecordRequest",
            "declaration": "export interface SessionFeedbackRecordRequest {\n    readonly sessionId: SessionId;\n    readonly text?: string;\n    readonly category?: FeedbackCategory;\n}"
          },
          {
            "name": "SessionFeedbackRecordResult",
            "declaration": "export type SessionFeedbackRecordResult = { readonly ok: true; readonly value: SessionFeedbackRecordValue; } | { readonly ok: false; readonly error: SessionFeedbackSessionNotFound; };"
          },
          {
            "name": "SessionFeedbackRecordValue",
            "declaration": "export interface SessionFeedbackRecordValue {\n    readonly recorded: true;\n}"
          },
          {
            "name": "SessionFeedbackSessionNotFound",
            "declaration": "export interface SessionFeedbackSessionNotFound {\n    readonly code: 'session-not-found';\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
