import { KNOWN_SESSION_EVENT_TYPES, SESSION_FORMAT_VERSION, Session, SessionId, SessionLogOffset } from "@deepseek-ai/dsh-session";
import { SessionFormatUnsupportedMigrationError, createSessionFormatCatalog } from "@deepseek-ai/dsh-session-format";
import { imageOffloadProjection } from "@deepseek-ai/dsh-compaction-image-offload/projection";
import { releasedV0SessionFormatCodec, releasedV1SessionFormatCodec, sessionFormatV0ToV1 } from "@deepseek-ai/dsh-session-format-v0-to-v1";
import { releasedV2SessionFormatCodec, sessionFormatV1ToV2 } from "@deepseek-ai/dsh-session-format-v1-to-v2";
import { assertReleasedV3Header, releasedV3SessionFormatCodec, restoreReleasedV3Artifact, sessionFormatV2ToV3 } from "@deepseek-ai/dsh-session-format-v2-to-v3";
import { RELEASED_V3_EVENT_TYPES, assertReleasedV4Header, createSessionFormatV3ToV4, releasedV4SessionFormatCodec, restoreReleasedV4Artifact, sessionFormatV3ToV4 } from "@deepseek-ai/dsh-session-format-v3-to-v4";
//#region lib/types/message-projections.js
/** Pure first-party message interpreters for detached current-format replay, including browser readers. */
/** Installed interpretation definitions; recovery listeners are mounted separately by their owning plugins. */
const currentSessionMessageProjections = [imageOffloadProjection];
//#endregion
//#region lib/types/current.js
/** Current installed Session validation used after vocabulary-aware format restoration. */
/**
* Validate current logical metadata through the installed Session package.
* @param header - detached current logical header.
* @returns nothing after successful validation.
*/
function validateInstalledCurrentSessionHeader(header) {
	if (header.version !== SESSION_FORMAT_VERSION) throw new Error(`installed Session format is v${SESSION_FORMAT_VERSION}, got v${header.version}`);
	Session.fromRestore(SessionId(header.id), [], header, SessionLogOffset(0), "detached");
}
/**
* Validate current header, event envelopes, messages, surface operations, and seed cut through the installed Session package.
* @param artifact - vocabulary-restored current logical artifact.
* @returns nothing after successful validation.
*/
function validateInstalledCurrentSessionArtifact(artifact) {
	if (artifact.header.version !== SESSION_FORMAT_VERSION) throw new Error(`installed Session format is v${SESSION_FORMAT_VERSION}, got v${artifact.header.version}`);
	Session.fromRestore(SessionId(artifact.header.id), artifact.events, artifact.header, SessionLogOffset(artifact.inheritedEventCount), "detached", currentSessionMessageProjections);
}
//#endregion
//#region lib/types/generated.js
/**
* GENERATED by `scripts/gen-session-format-catalog.ts` — do not edit by hand.
* The direct imports make historical readability independent of mounted plugins.
*/
/** Static assembly shared by current reads and parent-specific historical restoration. */
const sessionFormatCatalogOptions = {
	currentVersion: 4,
	codecs: [
		releasedV0SessionFormatCodec,
		releasedV1SessionFormatCodec,
		releasedV2SessionFormatCodec,
		releasedV3SessionFormatCodec,
		releasedV4SessionFormatCodec
	],
	currentEncoder: releasedV4SessionFormatCodec,
	migrations: [
		sessionFormatV0ToV1,
		sessionFormatV1ToV2,
		sessionFormatV2ToV3,
		sessionFormatV3ToV4
	],
	restoreCurrent(artifact) {
		const restored = restoreReleasedV4Artifact(artifact, KNOWN_SESSION_EVENT_TYPES);
		validateInstalledCurrentSessionArtifact(restored);
		return restored;
	},
	restoreTransformedCurrent(artifact) {
		return restoreReleasedV4Artifact(artifact, KNOWN_SESSION_EVENT_TYPES);
	},
	restoreCurrentHeader(header) {
		assertReleasedV4Header(header);
		validateInstalledCurrentSessionHeader(header);
		return header;
	}
};
/** Physical codec dispatch and complete adjacent chain, independent of mounted plugins. */
const sessionFormatCatalog = createSessionFormatCatalog(sessionFormatCatalogOptions);
//#endregion
//#region lib/types/children.js
/** Bind parent-specific child evidence into the static first-party migration inventory. */
/**
* Assemble a catalog whose V3→V4 edge knows one parent's historical children.
* @param children - complete child evidence retained unchanged for the catalog's lifetime; an empty array declares no children.
* @returns a catalog with independent restore state per artifact and unchanged current-format readers.
*/
function createSessionFormatCatalogWithChildren(children) {
	const migration = createSessionFormatV3ToV4(children);
	return createSessionFormatCatalog({
		...sessionFormatCatalogOptions,
		migrations: sessionFormatCatalogOptions.migrations.map((edge) => edge === sessionFormatV3ToV4 ? migration : edge)
	});
}
//#endregion
//#region lib/types/historical.js
/** Historical restoration for collecting migration prerequisites without recursively opening current Sessions. */
/** V0–V3 decoding for historical child identity; never publishes or completes parent catalogs. */
const historicalSessionFormatCatalog = createSessionFormatCatalog({
	currentVersion: 3,
	codecs: [
		releasedV0SessionFormatCodec,
		releasedV1SessionFormatCodec,
		releasedV2SessionFormatCodec,
		releasedV3SessionFormatCodec
	],
	currentEncoder: releasedV3SessionFormatCodec,
	migrations: [
		sessionFormatV0ToV1,
		sessionFormatV1ToV2,
		sessionFormatV2ToV3
	],
	restoreCurrent: (artifact) => restoreReleasedV3Artifact(artifact, RELEASED_V3_EVENT_TYPES),
	restoreTransformedCurrent: (artifact) => restoreReleasedV3Artifact(artifact, RELEASED_V3_EVENT_TYPES),
	restoreCurrentHeader(header) {
		assertReleasedV3Header(header);
		return header;
	}
});
//#endregion
export { SessionFormatUnsupportedMigrationError, createSessionFormatCatalogWithChildren, historicalSessionFormatCatalog, sessionFormatCatalog };
