/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_0$schema$value ??= z.string())
let _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_1$schema$value
const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_1$schema = () => (_deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_1$schema$value ??= z.string())
let _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_result$schema$value ??= z.string())
let _deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_parameter_0$schema$value ??= z.union([z.undefined(), z.string()]))
let _deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_result$schema$value ??= z.object({
  'path': z.string(),
  'home': z.string(),
  'crumbs': z.array(z.object({
  'name': z.string(),
  'path': z.string(),
  'hidden': z.boolean(),
})),
  'entries': z.array(z.object({
  'name': z.string(),
  'path': z.string(),
  'hidden': z.boolean(),
})),
  'truncated': z.boolean(),
}))
let _deepseek_ai_dsh_api_workspace_controller_directoryPicker_pick_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_pick_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_directoryPicker_pick_result$schema$value ??= z.union([z.literal(null), z.string()]))
let _deepseek_ai_dsh_api_workspace_controller_workspace_archiveSession_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_archiveSession_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_archiveSession_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'stopActivity': z.boolean().readonly().optional(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_archiveSession_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_archiveSession_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_archiveSession_result$schema$value ??= z.object({
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_create_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_create_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_create_parameter_0$schema$value ??= z.object({
  'path': z.string().readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_create_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_create_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_create_result$schema$value ??= z.object({
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
  'created': z.boolean().readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_delete_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_delete_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_delete_parameter_0$schema$value ??= z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_delete_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_delete_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_delete_result$schema$value ??= z.object({
  'deleted': z.literal(true).readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_follow_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_follow_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_follow_result$schema$value ??= z.union([z.object({
  'type': z.literal("baseline").readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
})).readonly(),
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'pinnedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
}), z.object({
  'type': z.literal("upsert").readonly(),
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
}), z.object({
  'type': z.literal("remove").readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'type': z.literal("order").readonly(),
  'workspaceIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}), z.object({
  'type': z.literal("archived").readonly(),
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}), z.object({
  'type': z.literal("pinned").readonly(),
  'pinnedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
})]))
let _deepseek_ai_dsh_api_workspace_controller_workspace_initializeDefault_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_initializeDefault_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_initializeDefault_result$schema$value ??= z.union([z.undefined(), z.object({
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
})]))
let _deepseek_ai_dsh_api_workspace_controller_workspace_insertBefore_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_insertBefore_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_insertBefore_parameter_0$schema$value ??= z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'beforeWorkspaceId': z.intersection(z.string(), z.unknown()).readonly().optional(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_insertBefore_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_insertBefore_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_insertBefore_result$schema$value ??= z.object({
  'workspaceIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_insertSessionBefore_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_insertSessionBefore_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_insertSessionBefore_parameter_0$schema$value ??= z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'beforeSessionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_insertSessionBefore_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_insertSessionBefore_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_insertSessionBefore_result$schema$value ??= z.object({
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_pinSession_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_pinSession_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_pinSession_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_pinSession_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_pinSession_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_pinSession_result$schema$value ??= z.object({
  'pinnedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_rename_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_rename_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_rename_parameter_0$schema$value ??= z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_rename_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_rename_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_rename_result$schema$value ??= z.object({
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_unarchiveSession_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_unarchiveSession_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_unarchiveSession_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_unarchiveSession_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_unarchiveSession_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_unarchiveSession_result$schema$value ??= z.object({
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_unpinSession_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_unpinSession_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_unpinSession_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}))
let _deepseek_ai_dsh_api_workspace_controller_workspace_unpinSession_result$schema$value
const _deepseek_ai_dsh_api_workspace_controller_workspace_unpinSession_result$schema = () => (_deepseek_ai_dsh_api_workspace_controller_workspace_unpinSession_result$schema$value ??= z.object({
  'pinnedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}))

export const TYPERT = {
  package: '@deepseek-ai/dsh-api-workspace-controller',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/createDirectory',
      service: 'directoryPickerController',
      namespace: 'directoryPicker',
      method: 'createDirectory',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/createDirectory:path',
            create: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_0$schema,
          },
        },
        {
          name: 'name',
          wire: 'name',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/createDirectory:name',
            create: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/createDirectory:result',
        create: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/directory-picker.ts","line":88,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/list',
      service: 'directoryPickerController',
      namespace: 'directoryPicker',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/list:path',
            create: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-directory-picker/types#DirectoryListing',
        create: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/directory-picker.ts","line":72,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/pick',
      service: 'directoryPickerController',
      namespace: 'directoryPicker',
      method: 'pick',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/pick:result',
        create: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_pick_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/directory-picker.ts","line":55,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/archiveSession',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'archiveSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceArchiveSessionRequest',
            create: _deepseek_ai_dsh_api_workspace_controller_workspace_archiveSession_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceArchiveValue',
        create: _deepseek_ai_dsh_api_workspace_controller_workspace_archiveSession_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":155,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/create',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceCreateRequest',
            create: _deepseek_ai_dsh_api_workspace_controller_workspace_create_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceCreateValue',
        create: _deepseek_ai_dsh_api_workspace_controller_workspace_create_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":86,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/delete',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceDeleteRequest',
            create: _deepseek_ai_dsh_api_workspace_controller_workspace_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceDeleteValue',
        create: _deepseek_ai_dsh_api_workspace_controller_workspace_delete_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":125,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/follow',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'follow',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceFollowFrame',
        create: _deepseek_ai_dsh_api_workspace_controller_workspace_follow_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":195,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/initializeDefault',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'initializeDefault',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller#workspace/initializeDefault:result',
        create: _deepseek_ai_dsh_api_workspace_controller_workspace_initializeDefault_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":99,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/insertBefore',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'insertBefore',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceInsertBeforeRequest',
            create: _deepseek_ai_dsh_api_workspace_controller_workspace_insertBefore_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceOrderValue',
        create: _deepseek_ai_dsh_api_workspace_controller_workspace_insertBefore_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":135,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/insertSessionBefore',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'insertSessionBefore',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceInsertSessionBeforeRequest',
            create: _deepseek_ai_dsh_api_workspace_controller_workspace_insertSessionBefore_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceValue',
        create: _deepseek_ai_dsh_api_workspace_controller_workspace_insertSessionBefore_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":145,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/pinSession',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'pinSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspacePinSessionRequest',
            create: _deepseek_ai_dsh_api_workspace_controller_workspace_pinSession_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspacePinValue',
        create: _deepseek_ai_dsh_api_workspace_controller_workspace_pinSession_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":175,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/rename',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'rename',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceRenameRequest',
            create: _deepseek_ai_dsh_api_workspace_controller_workspace_rename_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceValue',
        create: _deepseek_ai_dsh_api_workspace_controller_workspace_rename_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":115,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/unarchiveSession',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'unarchiveSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceUnarchiveSessionRequest',
            create: _deepseek_ai_dsh_api_workspace_controller_workspace_unarchiveSession_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceArchiveValue',
        create: _deepseek_ai_dsh_api_workspace_controller_workspace_unarchiveSession_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":165,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/unpinSession',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'unpinSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceUnpinSessionRequest',
            create: _deepseek_ai_dsh_api_workspace_controller_workspace_unpinSession_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspacePinValue',
        create: _deepseek_ai_dsh_api_workspace_controller_workspace_unpinSession_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":185,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host service backing the generated `ctx.remote.directoryPicker` namespace. The seam it exports is abstract and therefore never a Loader entry of its own, so this controller carries the wire verbs: one composed backend serves either the native chooser or the browse primitives, and a verb the composition cannot serve is refused rather than approximated.",
        "summary": "Host service backing the generated `ctx.remote.directoryPicker` namespace.",
        "tags": [],
        "jsDoc": "/**\n * Host service backing the generated `ctx.remote.directoryPicker` namespace. The\n * seam it exports is abstract and therefore never a Loader entry of its own, so\n * this controller carries the wire verbs: one composed backend serves either the\n * native chooser or the browse primitives, and a verb the composition cannot\n * serve is refused rather than approximated.\n */",
        "key": "directoryPickerController",
        "exportName": "DirectoryPickerController",
        "members": [
          {
            "kind": "method",
            "name": "pick",
            "signature": "@Remote('pick') async pick(signal: AbortSignal): Promise<string | null>",
            "summary": "Open the host's OS chooser for a Remote caller.",
            "jsDoc": "/**\n * Open the host's OS chooser for a Remote caller.\n * @param signal - caller lifetime; abort terminates the chooser.\n * @returns the chosen absolute path, or null when the operator cancels.\n */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') async list(path: string | undefined, signal: AbortSignal): Promise<DirectoryListing>",
            "summary": "List one directory level for a Remote caller's in-app browser.",
            "jsDoc": "/**\n * List one directory level for a Remote caller's in-app browser.\n * @param path - absolute directory to list; absent lists the home directory.\n * @param signal - caller lifetime; abort stops the backend's scan instead of\n *   letting it outlive a disconnected caller.\n * @returns the level's listing with its ancestry.\n */"
          },
          {
            "kind": "method",
            "name": "createDirectory",
            "signature": "@Remote('createDirectory') async createDirectory(path: string, name: string): Promise<string>",
            "summary": "Create one child directory for a Remote caller's in-app browser.",
            "jsDoc": "/**\n * Create one child directory for a Remote caller's in-app browser.\n * @param path - absolute existing parent directory.\n * @param name - single non-blank path segment.\n * @returns the created directory's absolute path.\n */"
          }
        ],
        "types": [
          {
            "name": "DirectoryEntry",
            "declaration": "export interface DirectoryEntry {\n    name: string;\n    path: string;\n    hidden: boolean;\n}"
          },
          {
            "name": "DirectoryListing",
            "declaration": "export interface DirectoryListing {\n    path: string;\n    home: string;\n    crumbs: DirectoryEntry[];\n    entries: DirectoryEntry[];\n    truncated: boolean;\n}"
          }
        ]
      },
      {
        "description": "Host service backing the generated `ctx.remote.workspace` namespace.",
        "summary": "Host service backing the generated `ctx.remote.workspace` namespace.",
        "tags": [],
        "jsDoc": "/** Host service backing the generated `ctx.remote.workspace` namespace. */",
        "key": "workspaceController",
        "exportName": "WorkspaceController",
        "members": [
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote('create') create(request: WorkspaceCreateRequest): Promise<WorkspaceCreateValue>",
            "summary": "Create or idempotently resolve one Workspace over an existing directory.",
            "jsDoc": "/**\n * Create or idempotently resolve one Workspace over an existing directory.\n * @param request - directory path to register.\n * @returns the Workspace and whether this call created it.\n */"
          },
          {
            "kind": "method",
            "name": "initializeDefault",
            "signature": "@Remote('initializeDefault') async initializeDefault(signal: AbortSignal): Promise<WorkspaceValue | undefined>",
            "summary": "Initialize or reuse the default Workspace during first-use startup.",
            "jsDoc": "/**\n * Initialize or reuse the default Workspace during first-use startup. The\n * directory name is fixed, so the Host never renames or relocates an\n * existing default; its initial title is that same name, which browser\n * consumers label in the reader's language.\n * @param signal - caller lifetime; cancels native directory lookup.\n * @returns the durable Workspace, or undefined when first-use initialization is ineligible; creates no Session or message.\n */"
          },
          {
            "kind": "method",
            "name": "rename",
            "signature": "@Remote('rename') rename(request: WorkspaceRenameRequest): Promise<WorkspaceValue>",
            "summary": "Rename one Workspace to a unique non-blank title.",
            "jsDoc": "/**\n * Rename one Workspace to a unique non-blank title.\n * @param request - Workspace identity and proposed title.\n * @returns the updated Workspace projection.\n */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote('delete') delete(request: WorkspaceDeleteRequest): Promise<WorkspaceDeleteValue>",
            "summary": "Remove one Workspace registration while retaining files and Sessions.",
            "jsDoc": "/**\n * Remove one Workspace registration while retaining files and Sessions.\n * @param request - Workspace identity to remove.\n * @returns deletion confirmation.\n */"
          },
          {
            "kind": "method",
            "name": "insertBefore",
            "signature": "@Remote('insertBefore') insertBefore(request: WorkspaceInsertBeforeRequest): Promise<WorkspaceOrderValue>",
            "summary": "Move one Workspace within the registry display order.",
            "jsDoc": "/**\n * Move one Workspace within the registry display order.\n * @param request - moved Workspace and optional anchor.\n * @returns the complete resulting Workspace order.\n */"
          },
          {
            "kind": "method",
            "name": "insertSessionBefore",
            "signature": "@Remote('insertSessionBefore') insertSessionBefore(request: WorkspaceInsertSessionBeforeRequest): Promise<WorkspaceValue>",
            "summary": "Move one accounted Session within a Workspace.",
            "jsDoc": "/**\n * Move one accounted Session within a Workspace.\n * @param request - Workspace, Session, and optional anchor identities.\n * @returns the updated Workspace projection.\n */"
          },
          {
            "kind": "method",
            "name": "archiveSession",
            "signature": "@Remote('archiveSession') archiveSession(request: WorkspaceArchiveSessionRequest): Promise<WorkspaceArchiveValue>",
            "summary": "Hide one known Session from Workspace grouping surfaces.",
            "jsDoc": "/**\n * Hide one known Session from Workspace grouping surfaces.\n * @param request - Session identity to archive.\n * @returns the complete resulting archive set.\n */"
          },
          {
            "kind": "method",
            "name": "unarchiveSession",
            "signature": "@Remote('unarchiveSession') unarchiveSession(request: WorkspaceUnarchiveSessionRequest): Promise<WorkspaceArchiveValue>",
            "summary": "Restore one archived Session to Workspace grouping surfaces.",
            "jsDoc": "/**\n * Restore one archived Session to Workspace grouping surfaces.\n * @param request - Session identity to unarchive.\n * @returns the complete resulting archive set.\n */"
          },
          {
            "kind": "method",
            "name": "pinSession",
            "signature": "@Remote('pinSession') pinSession(request: WorkspacePinSessionRequest): Promise<WorkspacePinValue>",
            "summary": "Surface one known unarchived Session ahead of unpinned Sessions.",
            "jsDoc": "/**\n * Surface one known unarchived Session ahead of unpinned Sessions.\n * @param request - Session identity to pin.\n * @returns the complete resulting pin set, most recently pinned first.\n */"
          },
          {
            "kind": "method",
            "name": "unpinSession",
            "signature": "@Remote('unpinSession') unpinSession(request: WorkspaceUnpinSessionRequest): Promise<WorkspacePinValue>",
            "summary": "Remove one Session's pin without changing its saved Session order.",
            "jsDoc": "/**\n * Remove one Session's pin without changing its saved Session order.\n * @param request - Session identity to unpin.\n * @returns the complete resulting pin set, most recently pinned first.\n */"
          },
          {
            "kind": "method",
            "name": "follow",
            "signature": "@Remote({ mode: 'stream' }) follow(signal: AbortSignal): AsyncIterable<WorkspaceFollowFrame>",
            "summary": "Stream a complete Workspace baseline followed by ordered increments.",
            "jsDoc": "/**\n * Stream a complete Workspace baseline followed by ordered increments.\n * @param signal - generation cancellation.\n * @returns baseline followed by ordered Workspace increments.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "WorkspaceArchiveSessionRequest",
            "declaration": "export interface WorkspaceArchiveSessionRequest {\n    readonly sessionId: SessionId;\n    readonly stopActivity?: boolean;\n}"
          },
          {
            "name": "WorkspaceArchiveValue",
            "declaration": "export interface WorkspaceArchiveValue {\n    readonly archivedSessionIds: readonly SessionId[];\n}"
          },
          {
            "name": "WorkspaceBaseline",
            "declaration": "export interface WorkspaceBaseline {\n    readonly items: readonly WorkspaceView[];\n    readonly archivedSessionIds: readonly SessionId[];\n    readonly pinnedSessionIds: readonly SessionId[];\n}"
          },
          {
            "name": "WorkspaceCreateRequest",
            "declaration": "export interface WorkspaceCreateRequest {\n    readonly path: string;\n}"
          },
          {
            "name": "WorkspaceCreateValue",
            "declaration": "export interface WorkspaceCreateValue {\n    readonly workspace: WorkspaceView;\n    readonly created: boolean;\n}"
          },
          {
            "name": "WorkspaceDeleteRequest",
            "declaration": "export interface WorkspaceDeleteRequest {\n    readonly workspaceId: WorkspaceId;\n}"
          },
          {
            "name": "WorkspaceDeleteValue",
            "declaration": "export interface WorkspaceDeleteValue {\n    readonly deleted: true;\n}"
          },
          {
            "name": "WorkspaceFollowFrame",
            "declaration": "export type WorkspaceFollowFrame = { readonly type: 'baseline'; readonly value: WorkspaceBaseline; } | WorkspaceFollowIncrement;"
          },
          {
            "name": "WorkspaceFollowIncrement",
            "declaration": "export type WorkspaceFollowIncrement = { readonly type: 'upsert'; readonly workspace: WorkspaceView; } | { readonly type: 'remove'; readonly workspaceId: WorkspaceId; } | { readonly type: 'order'; readonly workspaceIds: readonly WorkspaceId[]; } | { readonly type: 'archived'; readonly archivedSessionIds: readonly SessionId[]; } | { readonly type: 'pinned'; readonly pinnedSessionIds: readonly SessionId[]; };"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = Branded<'WorkspaceId'>;"
          },
          {
            "name": "WorkspaceInsertBeforeRequest",
            "declaration": "export interface WorkspaceInsertBeforeRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly beforeWorkspaceId?: WorkspaceId;\n}"
          },
          {
            "name": "WorkspaceInsertSessionBeforeRequest",
            "declaration": "export interface WorkspaceInsertSessionBeforeRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly sessionId: SessionId;\n    readonly beforeSessionId?: SessionId;\n}"
          },
          {
            "name": "WorkspaceOrderValue",
            "declaration": "export interface WorkspaceOrderValue {\n    readonly workspaceIds: readonly WorkspaceId[];\n}"
          },
          {
            "name": "WorkspacePinSessionRequest",
            "declaration": "export interface WorkspacePinSessionRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "WorkspacePinValue",
            "declaration": "export interface WorkspacePinValue {\n    readonly pinnedSessionIds: readonly SessionId[];\n}"
          },
          {
            "name": "WorkspaceRenameRequest",
            "declaration": "export interface WorkspaceRenameRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly title: string;\n}"
          },
          {
            "name": "WorkspaceUnarchiveSessionRequest",
            "declaration": "export interface WorkspaceUnarchiveSessionRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "WorkspaceUnpinSessionRequest",
            "declaration": "export interface WorkspaceUnpinSessionRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "WorkspaceValue",
            "declaration": "export interface WorkspaceValue {\n    readonly workspace: WorkspaceView;\n}"
          },
          {
            "name": "WorkspaceView",
            "declaration": "export interface WorkspaceView {\n    readonly workspaceId: WorkspaceId;\n    readonly path: string;\n    readonly title: string;\n    readonly sessionIds: readonly SessionId[];\n    readonly createdAt: string;\n    readonly updatedAt: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
