/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_0$schema$value
const _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_0$schema = () => (_deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_1$schema$value
const _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_1$schema = () => (_deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_1$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_2$schema$value
const _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_2$schema = () => (_deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_2$schema$value ??= z.object({
  'version': z.string().readonly(),
  'locale': z.string().readonly(),
  'timezoneOffsetSeconds': z.number().readonly(),
}))
let _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_result$schema$value
const _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_result$schema = () => (_deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_result$schema$value ??= z.boolean())
let _deepseek_ai_dsh_api_account_controller_account_cancelSignIn_parameter_0$schema$value
const _deepseek_ai_dsh_api_account_controller_account_cancelSignIn_parameter_0$schema = () => (_deepseek_ai_dsh_api_account_controller_account_cancelSignIn_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_api_account_controller_account_cancelSignIn_result$schema$value
const _deepseek_ai_dsh_api_account_controller_account_cancelSignIn_result$schema = () => (_deepseek_ai_dsh_api_account_controller_account_cancelSignIn_result$schema$value ??= z.object({
  'status': z.union([z.literal("signed-out"), z.literal("credential-stored")]).readonly(),
  'links': z.object({
  'usageUrl': z.string().readonly(),
  'topUpUrl': z.string().readonly(),
}).readonly(),
  'attempt': z.union([z.literal(null), z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'phase': z.union([z.literal("initializing"), z.literal("waiting-browser"), z.literal("exchanging"), z.literal("committing"), z.literal("succeeded"), z.literal("cancelled"), z.literal("expired"), z.literal("failed")]).readonly(),
  'authorizeUrl': z.string().readonly().optional(),
  'expiresAt': z.number().readonly().optional(),
  'errorCode': z.union([z.literal("expired"), z.literal("network"), z.literal("protocol"), z.literal("storage")]).readonly().optional(),
})]).readonly(),
}))
let _deepseek_ai_dsh_api_account_controller_account_getBalance_parameter_0$schema$value
const _deepseek_ai_dsh_api_account_controller_account_getBalance_parameter_0$schema = () => (_deepseek_ai_dsh_api_account_controller_account_getBalance_parameter_0$schema$value ??= z.object({
  'version': z.string().readonly(),
  'locale': z.string().readonly(),
  'timezoneOffsetSeconds': z.number().readonly(),
}))
let _deepseek_ai_dsh_api_account_controller_account_getBalance_result$schema$value
const _deepseek_ai_dsh_api_account_controller_account_getBalance_result$schema = () => (_deepseek_ai_dsh_api_account_controller_account_getBalance_result$schema$value ??= z.union([z.literal(null), z.object({
  'status': z.literal("ready").readonly(),
  'value': z.array(z.object({
  'currency': z.union([z.literal("CNY"), z.literal("USD")]).readonly(),
  'balance': z.string().readonly(),
})).readonly(),
  'bonusWallets': z.array(z.object({
  'currency': z.union([z.literal("CNY"), z.literal("USD")]).readonly(),
  'balance': z.string().readonly(),
})).readonly(),
}), z.object({
  'status': z.literal("failed").readonly(),
})]))
let _deepseek_ai_dsh_api_account_controller_account_getProfile_parameter_0$schema$value
const _deepseek_ai_dsh_api_account_controller_account_getProfile_parameter_0$schema = () => (_deepseek_ai_dsh_api_account_controller_account_getProfile_parameter_0$schema$value ??= z.object({
  'version': z.string().readonly(),
  'locale': z.string().readonly(),
  'timezoneOffsetSeconds': z.number().readonly(),
}))
let _deepseek_ai_dsh_api_account_controller_account_getProfile_result$schema$value
const _deepseek_ai_dsh_api_account_controller_account_getProfile_result$schema = () => (_deepseek_ai_dsh_api_account_controller_account_getProfile_result$schema$value ??= z.union([z.literal(null), z.object({
  'status': z.literal("ready").readonly(),
  'value': z.object({
  'id': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'name': z.union([z.literal(null), z.string()]).readonly(),
  'contact': z.union([z.literal(null), z.string()]).readonly(),
  'avatarUrl': z.union([z.literal(null), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'status': z.literal("failed").readonly(),
})]))
let _deepseek_ai_dsh_api_account_controller_account_getState_result$schema$value
const _deepseek_ai_dsh_api_account_controller_account_getState_result$schema = () => (_deepseek_ai_dsh_api_account_controller_account_getState_result$schema$value ??= z.object({
  'status': z.union([z.literal("signed-out"), z.literal("credential-stored")]).readonly(),
  'links': z.object({
  'usageUrl': z.string().readonly(),
  'topUpUrl': z.string().readonly(),
}).readonly(),
  'attempt': z.union([z.literal(null), z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'phase': z.union([z.literal("initializing"), z.literal("waiting-browser"), z.literal("exchanging"), z.literal("committing"), z.literal("succeeded"), z.literal("cancelled"), z.literal("expired"), z.literal("failed")]).readonly(),
  'authorizeUrl': z.string().readonly().optional(),
  'expiresAt': z.number().readonly().optional(),
  'errorCode': z.union([z.literal("expired"), z.literal("network"), z.literal("protocol"), z.literal("storage")]).readonly().optional(),
})]).readonly(),
}))
let _deepseek_ai_dsh_api_account_controller_account_getUnnotifiedBonuses_parameter_0$schema$value
const _deepseek_ai_dsh_api_account_controller_account_getUnnotifiedBonuses_parameter_0$schema = () => (_deepseek_ai_dsh_api_account_controller_account_getUnnotifiedBonuses_parameter_0$schema$value ??= z.object({
  'version': z.string().readonly(),
  'locale': z.string().readonly(),
  'timezoneOffsetSeconds': z.number().readonly(),
}))
let _deepseek_ai_dsh_api_account_controller_account_getUnnotifiedBonuses_result$schema$value
const _deepseek_ai_dsh_api_account_controller_account_getUnnotifiedBonuses_result$schema = () => (_deepseek_ai_dsh_api_account_controller_account_getUnnotifiedBonuses_result$schema$value ??= z.union([z.literal(null), z.object({
  'accountId': z.intersection(z.string(), z.unknown()).readonly(),
  'bonuses': z.array(z.object({
  'orderId': z.intersection(z.string(), z.unknown()).readonly(),
  'campaign': z.string().readonly(),
  'amount': z.string().readonly(),
  'currency': z.union([z.literal("CNY"), z.literal("USD")]).readonly(),
  'grantedAt': z.string().readonly(),
  'expiresAt': z.string().readonly(),
  'message': z.string().readonly(),
})).readonly(),
})]))
let _deepseek_ai_dsh_api_account_controller_account_hasRunningAccountTasks_result$schema$value
const _deepseek_ai_dsh_api_account_controller_account_hasRunningAccountTasks_result$schema = () => (_deepseek_ai_dsh_api_account_controller_account_hasRunningAccountTasks_result$schema$value ??= z.boolean())
let _deepseek_ai_dsh_api_account_controller_account_signOut_parameter_0$schema$value
const _deepseek_ai_dsh_api_account_controller_account_signOut_parameter_0$schema = () => (_deepseek_ai_dsh_api_account_controller_account_signOut_parameter_0$schema$value ??= z.object({
  'version': z.string().readonly(),
  'locale': z.string().readonly(),
  'timezoneOffsetSeconds': z.number().readonly(),
}))
let _deepseek_ai_dsh_api_account_controller_account_signOut_result$schema$value
const _deepseek_ai_dsh_api_account_controller_account_signOut_result$schema = () => (_deepseek_ai_dsh_api_account_controller_account_signOut_result$schema$value ??= z.object({
  'status': z.union([z.literal("signed-out"), z.literal("credential-stored")]).readonly(),
  'links': z.object({
  'usageUrl': z.string().readonly(),
  'topUpUrl': z.string().readonly(),
}).readonly(),
  'attempt': z.union([z.literal(null), z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'phase': z.union([z.literal("initializing"), z.literal("waiting-browser"), z.literal("exchanging"), z.literal("committing"), z.literal("succeeded"), z.literal("cancelled"), z.literal("expired"), z.literal("failed")]).readonly(),
  'authorizeUrl': z.string().readonly().optional(),
  'expiresAt': z.number().readonly().optional(),
  'errorCode': z.union([z.literal("expired"), z.literal("network"), z.literal("protocol"), z.literal("storage")]).readonly().optional(),
})]).readonly(),
}))
let _deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_0$schema$value
const _deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_0$schema = () => (_deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_0$schema$value ??= z.object({
  'version': z.string().readonly(),
  'locale': z.string().readonly(),
  'timezoneOffsetSeconds': z.number().readonly(),
}))
let _deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_1$schema$value
const _deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_1$schema = () => (_deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_1$schema$value ??= z.string())
let _deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_2$schema$value
const _deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_2$schema = () => (_deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_2$schema$value ??= z.union([z.literal("web"), z.literal("desktop")]))
let _deepseek_ai_dsh_api_account_controller_account_startSignIn_result$schema$value
const _deepseek_ai_dsh_api_account_controller_account_startSignIn_result$schema = () => (_deepseek_ai_dsh_api_account_controller_account_startSignIn_result$schema$value ??= z.object({
  'status': z.union([z.literal("signed-out"), z.literal("credential-stored")]).readonly(),
  'links': z.object({
  'usageUrl': z.string().readonly(),
  'topUpUrl': z.string().readonly(),
}).readonly(),
  'attempt': z.union([z.literal(null), z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'phase': z.union([z.literal("initializing"), z.literal("waiting-browser"), z.literal("exchanging"), z.literal("committing"), z.literal("succeeded"), z.literal("cancelled"), z.literal("expired"), z.literal("failed")]).readonly(),
  'authorizeUrl': z.string().readonly().optional(),
  'expiresAt': z.number().readonly().optional(),
  'errorCode': z.union([z.literal("expired"), z.literal("network"), z.literal("protocol"), z.literal("storage")]).readonly().optional(),
})]).readonly(),
}))
let _deepseek_ai_dsh_api_account_controller_account_watch_result$schema$value
const _deepseek_ai_dsh_api_account_controller_account_watch_result$schema = () => (_deepseek_ai_dsh_api_account_controller_account_watch_result$schema$value ??= z.object({
  'status': z.union([z.literal("signed-out"), z.literal("credential-stored")]).readonly(),
  'links': z.object({
  'usageUrl': z.string().readonly(),
  'topUpUrl': z.string().readonly(),
}).readonly(),
  'attempt': z.union([z.literal(null), z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'phase': z.union([z.literal("initializing"), z.literal("waiting-browser"), z.literal("exchanging"), z.literal("committing"), z.literal("succeeded"), z.literal("cancelled"), z.literal("expired"), z.literal("failed")]).readonly(),
  'authorizeUrl': z.string().readonly().optional(),
  'expiresAt': z.number().readonly().optional(),
  'errorCode': z.union([z.literal("expired"), z.literal("network"), z.literal("protocol"), z.literal("storage")]).readonly().optional(),
})]).readonly(),
}))
let _deepseek_ai_dsh_api_account_controller_account_watchExpiry_result$schema$value
const _deepseek_ai_dsh_api_account_controller_account_watchExpiry_result$schema = () => (_deepseek_ai_dsh_api_account_controller_account_watchExpiry_result$schema$value ??= z.literal("session-expired"))

export const TYPERT = {
  package: '@deepseek-ai/dsh-api-account-controller',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-api-account-controller#account/ackBonusNotified',
      service: 'accountController',
      namespace: 'account',
      method: 'ackBonusNotified',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'accountId',
          wire: 'accountId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountUserId',
            create: _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_0$schema,
          },
        },
        {
          name: 'orderId',
          wire: 'orderId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountBonusOrderId',
            create: _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_1$schema,
          },
        },
        {
          name: 'client',
          wire: 'client',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountClientMetadata',
            create: _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-account-controller#account/ackBonusNotified:result',
        create: _deepseek_ai_dsh_api_account_controller_account_ackBonusNotified_result$schema,
      },
      sourceLocation: {"file":"packages/api/account-controller/src/index.ts","line":55,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-account-controller#account/cancelSignIn',
      service: 'accountController',
      namespace: 'account',
      method: 'cancelSignIn',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'attemptId',
          wire: 'attemptId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#SignInAttemptId',
            create: _deepseek_ai_dsh_api_account_controller_account_cancelSignIn_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountView',
        create: _deepseek_ai_dsh_api_account_controller_account_cancelSignIn_result$schema,
      },
      sourceLocation: {"file":"packages/api/account-controller/src/index.ts","line":75,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-account-controller#account/getBalance',
      service: 'accountController',
      namespace: 'account',
      method: 'getBalance',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'client',
          wire: 'client',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountClientMetadata',
            create: _deepseek_ai_dsh_api_account_controller_account_getBalance_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-account-controller#account/getBalance:result',
        create: _deepseek_ai_dsh_api_account_controller_account_getBalance_result$schema,
      },
      sourceLocation: {"file":"packages/api/account-controller/src/index.ts","line":35,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-account-controller#account/getProfile',
      service: 'accountController',
      namespace: 'account',
      method: 'getProfile',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'client',
          wire: 'client',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountClientMetadata',
            create: _deepseek_ai_dsh_api_account_controller_account_getProfile_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-account-controller#account/getProfile:result',
        create: _deepseek_ai_dsh_api_account_controller_account_getProfile_result$schema,
      },
      sourceLocation: {"file":"packages/api/account-controller/src/index.ts","line":26,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-account-controller#account/getState',
      service: 'accountController',
      namespace: 'account',
      method: 'getState',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountView',
        create: _deepseek_ai_dsh_api_account_controller_account_getState_result$schema,
      },
      sourceLocation: {"file":"packages/api/account-controller/src/index.ts","line":19,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-account-controller#account/getUnnotifiedBonuses',
      service: 'accountController',
      namespace: 'account',
      method: 'getUnnotifiedBonuses',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'client',
          wire: 'client',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountClientMetadata',
            create: _deepseek_ai_dsh_api_account_controller_account_getUnnotifiedBonuses_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-account-controller#account/getUnnotifiedBonuses:result',
        create: _deepseek_ai_dsh_api_account_controller_account_getUnnotifiedBonuses_result$schema,
      },
      sourceLocation: {"file":"packages/api/account-controller/src/index.ts","line":44,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-account-controller#account/hasRunningAccountTasks',
      service: 'accountController',
      namespace: 'account',
      method: 'hasRunningAccountTasks',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-account-controller#account/hasRunningAccountTasks:result',
        create: _deepseek_ai_dsh_api_account_controller_account_hasRunningAccountTasks_result$schema,
      },
      sourceLocation: {"file":"packages/api/account-controller/src/index.ts","line":81,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-account-controller#account/signOut',
      service: 'accountController',
      namespace: 'account',
      method: 'signOut',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'client',
          wire: 'client',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountClientMetadata',
            create: _deepseek_ai_dsh_api_account_controller_account_signOut_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountView',
        create: _deepseek_ai_dsh_api_account_controller_account_signOut_result$schema,
      },
      sourceLocation: {"file":"packages/api/account-controller/src/index.ts","line":90,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-account-controller#account/startSignIn',
      service: 'accountController',
      namespace: 'account',
      method: 'startSignIn',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'client',
          wire: 'client',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountClientMetadata',
            create: _deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_0$schema,
          },
        },
        {
          name: 'callbackOrigin',
          wire: 'callbackOrigin',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-account-controller#account/startSignIn:callbackOrigin',
            create: _deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_1$schema,
          },
        },
        {
          name: 'loginSource',
          wire: 'loginSource',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-account-controller#account/startSignIn:loginSource',
            create: _deepseek_ai_dsh_api_account_controller_account_startSignIn_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountView',
        create: _deepseek_ai_dsh_api_account_controller_account_startSignIn_result$schema,
      },
      sourceLocation: {"file":"packages/api/account-controller/src/index.ts","line":66,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-account-controller#account/watch',
      service: 'accountController',
      namespace: 'account',
      method: 'watch',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepseek-account/types#AccountView',
        create: _deepseek_ai_dsh_api_account_controller_account_watch_result$schema,
      },
      sourceLocation: {"file":"packages/api/account-controller/src/index.ts","line":119,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-account-controller#account/watchExpiry',
      service: 'accountController',
      namespace: 'account',
      method: 'watchExpiry',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-account-controller#account/watchExpiry:result',
        create: _deepseek_ai_dsh_api_account_controller_account_watchExpiry_result$schema,
      },
      sourceLocation: {"file":"packages/api/account-controller/src/index.ts","line":97,"column":10},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
