import { Service } from "@deepseek-ai/cordis";
import { isAbsolute } from "node:path";
import { brandNumber, brandString } from "@deepseek-ai/dsh-brand";
import { assertNever, deepFreeze, snapshotJsonValue } from "@deepseek-ai/dsh-util-values";
import { scopeOf, scopeTarget } from "@deepseek-ai/dsh-scope";
import { callConfigEquals } from "@deepseek-ai/dsh-llm";
//#region lib/types/types.js
/**
* Brand a string as a {@link SessionId}.
* @param id - the raw session id string.
* @returns the same string with the session-id brand.
*/
function SessionId(id) {
	return brandString(id);
}
/**
* Admit a numeric value as an existing Session event position.
* @param value - non-negative safe integer admitted by the owning log operation.
* @returns the same number with the Session-sequence brand.
*/
function SessionSeq(value) {
	if (!Number.isSafeInteger(value) || value < 0 || Object.is(value, -0)) throw new TypeError(`SessionSeq must be a non-negative safe integer, got ${String(value)}`);
	return brandNumber(value);
}
/**
* Admit a numeric value as a Session log offset.
* @param value - non-negative safe integer used as a gap or prefix length.
* @returns the same number with the Session-log-offset brand.
*/
function SessionLogOffset(value) {
	if (!Number.isSafeInteger(value) || value < 0 || Object.is(value, -0)) throw new TypeError(`SessionLogOffset must be a non-negative safe integer, got ${String(value)}`);
	return brandNumber(value);
}
/**
* Current logical Session format version, stamped into every newly written
* {@link SessionHeader}. Current Session and persistence code accept only this
* value; header-only readers classify supported historical formats, while an
* event-body read composes the build-static adjacent chain and publishes only
* this final generation before constructing a Session.
*
* The version is a single monotonic integer with no major/minor split. Whether
* a bump is needed is decided by what the WRITER emits, never by what a newer
* reader can accept: bump exactly when an older runtime could no longer handle
* a new log with full semantic correctness ("parses without error" is not
* correctness — silently skipping content that shapes reconstruction is a
* wrong read). Only structural changes reach that bar: the header shape, the
* {@link SessionEvent} envelope, core event semantics, or the surface
* mechanism (the {@link SurfaceEventType} set and {@link SurfaceOp} variants).
* Adding an ordinary event type does not bump — the per-event
* {@link SessionEvent.ignorable} guard covers vocabulary growth instead. When
* in doubt, bump: a near-identity upgrade step is almost free, a missed bump
* makes older runtimes read new logs wrong silently. The released migration,
* immutable prior-generation, and current fast-path rules are recorded in
* `.agents/notes/implemented/architecture/2026-08-31-released-session-format-migrations.md`.
*/
const SESSION_FORMAT_VERSION = 4;
//#endregion
//#region lib/types/known-event-types.js
/**
* GENERATED by `scripts/gen-persistence-catalog.ts` — do not edit by hand; run
* `pnpm run gen-persistence-catalog` to regenerate (verified fresh by
* `pnpm run verify-persistence-catalog`, part of `doc-sync`).
* @module @deepseek-ai/dsh-session/known-event-types
*/
/**
* Every `SessionEventMap` member declared in this repository — the event
* vocabulary this build understands. The persistence read path refuses to
* interpret a log containing a type outside this set unless the event
* carries the envelope's `ignorable` marker (see `SessionEvent.ignorable`
* in `./types.ts`): such a log was likely written by a newer harness, and
* silently skipping a required event would reconstruct a wrong session.
* Downstream (out-of-repo) plugin events are outside this list by
* construction. The persisted `SessionEvent.ignorable` marker is the
* compatibility mechanism; event-name registration was rejected because
* it does not classify omission safety and would make reads
* composition-dependent. The rationale is in
* `.agents/notes/implemented/architecture/2026-08-30-retain-ignorable-external-session-events.md`.
*/
const KNOWN_SESSION_EVENT_TYPES = new Set([
	"agent-preset/selected",
	"agent/inbox/spliced",
	"approval/asked",
	"approval/decided",
	"approval/policy",
	"assistant/attempt",
	"assistant/message",
	"command/done",
	"command/run",
	"compaction/end",
	"compaction/prune",
	"compaction/start",
	"compaction/summary",
	"deliverables/presented",
	"developer/message",
	"feedback/message-delete",
	"feedback/message-put",
	"feedback/record",
	"goal/change",
	"hook/invoked",
	"hook/result",
	"image/offload",
	"llm/retry",
	"llm/retry-started",
	"model/selection",
	"permission/preset",
	"plan/mode",
	"request/context",
	"request/header",
	"sandbox/mode",
	"schedule/change",
	"session-log-deepseek/delivery-accepted",
	"session/end-seed",
	"session/title",
	"session/title-llm-request",
	"step/end",
	"step/start",
	"subagent/catalog",
	"subagent/descriptor",
	"subagent/model-selection-policy",
	"system/message",
	"team/member",
	"team/message/delivered",
	"team/message/queued",
	"team/task",
	"todo/write",
	"tool-workflow/agent-end",
	"tool-workflow/agent-start",
	"tool-workflow/run-end",
	"tool-workflow/run-start",
	"tool/call",
	"tool/ptc-dispatch",
	"tool/ptc-dispatch-start",
	"tool/result",
	"turn/end",
	"turn/start",
	"user/message",
	"web/deepseek-search-llm-request",
	"workspace/changes"
]);
/** Event types whose model-visible effects require an explicit pure interpreter. */
const MESSAGE_PROJECTION_EVENT_TYPES = new Set(["image/offload"]);
//#endregion
//#region lib/types/surface.js
/**
* Surface layer on top of the session event log: an ordered view of events
* that produce LLM messages. The append-only log remains the source of truth.
*
* Browser-safe: web clients consume this subpath export, so it must stay free
* of `node:` imports (they break the vite bundle).
*
* @module @deepseek-ai/dsh-session/surface
*/
/** Runtime counterpart of the message-producing event union. */
const SURFACE_EVENT_TYPES = new Set([
	"system/message",
	"developer/message",
	"user/message",
	"assistant/message",
	"tool/result"
]);
/**
* Whether an event type can join the model-visible surface.
* @param type - event type to test.
* @returns true for one of the message-producing event types.
*/
function isSurfaceEligibleType(type) {
	return SURFACE_EVENT_TYPES.has(type);
}
/**
* Narrow an event to a surface-eligible event carrying its required marker.
* @param event - event to test.
* @returns true when both the type and marker identify a surface event.
*/
function isSurfaceEvent(event) {
	if (!SURFACE_EVENT_TYPES.has(event.type)) return false;
	return event.surfaceOp !== void 0;
}
/**
* Narrow an event to an append-origin surface event: one that entered the
* surface at its own log position and was never itself a replacement copy.
*
* The model-visible surface deliberately shadows replaced ranges, so it is the
* wrong source for a human transcript — a landed replacement would erase
* conversation the user already saw. Append-origin events are that transcript's
* durable source material; replacement copies stay model-only.
* @param event - event to test.
* @returns true when the event appended to the surface tail.
*/
function isAppendSurfaceEvent(event) {
	return isSurfaceEvent(event) && event.surfaceOp === "append";
}
/**
* Narrow an event to a surface replacement: a node that shadowed an existing
* surface range instead of appending to the tail. The counterpart of
* {@link isAppendSurfaceEvent} over the two {@link SurfaceOp} variants.
* @param event - event to test.
* @returns true when the event replaced a surface range.
*/
function isReplacementSurfaceEvent(event) {
	return isSurfaceEvent(event) && event.surfaceOp !== "append";
}
/**
* Project a single event into the LLM message it derives to, or null when it
* produces none — a non-surface event (attempt, boundary, log-only record) or an
* empty-content system, developer, or assistant message. A caller
* reconstructing model input supplies the same prefix's `projectedMessages`
* from {@link foldSurface}; without that map this function reads original
* event content. Session instance methods apply the live projection. Messages
* are immutable and unchanged content retains its durable identity.
* @param event - the event to project.
* @param projectedMessages - message projections from the same log prefix's surface fold.
* @returns the derived message, or null when the event produces none.
*/
function deriveEventMessage(event, projectedMessages) {
	const projected = projectedMessages?.get(event.seq);
	if (projected !== void 0) return projected;
	switch (event.type) {
		case "user/message": return event.data;
		case "system/message":
		case "developer/message":
		case "assistant/message":
			if (event.data.message.content.length === 0) return null;
			return event.data.message;
		case "tool/result": return event.data.message;
		default: return null;
	}
}
/** Whether a payload field is a JSON object rather than an array or scalar. */
function isRecord(value) {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}
/**
* Reject noncanonical request-header fields, developer roles/content, and contradictory tool failure metadata.
* This does not validate complete event payloads or embedded provider streams.
* @param event - event whose locally related payload fields are inspected.
* @param subject - event location to include in validation errors.
* @throws when request-header fields, developer roles/content, or tool failure metadata are invalid.
*/
function validateSessionEventData(event, subject) {
	const data = event.data;
	if (SURFACE_EVENT_TYPES.has(event.type) && isRecord(data)) {
		const message = event.type === "user/message" ? data : data["message"];
		if (isRecord(message)) {
			if (event.type === "developer/message" !== (message["role"] === "developer")) throw new Error(`${subject} developer/message and developer role must occur together`);
			if (message["role"] !== "developer" && Array.isArray(message["content"]) && message["content"].some((block) => isRecord(block) && (block["type"] === "tool-addition" || block["type"] === "tool-removal"))) throw new Error(`${subject} tool-change blocks require developer role`);
			if (event.type === "developer/message" && Array.isArray(message["content"])) {
				let hasAdditions = false;
				for (const block of message["content"]) {
					if (!isRecord(block) || block["type"] !== "tool-addition" && block["type"] !== "tool-removal") continue;
					if (typeof block["toolName"] !== "string" || block["toolName"].length === 0) throw new Error(`${subject} ${block["type"]} requires a nonempty toolName`);
					if (block["type"] === "tool-addition") {
						hasAdditions = true;
						if (Object.hasOwn(block, "tool")) throw new Error(`${subject} tool-addition must omit inline tool definitions`);
					}
				}
				if (hasAdditions ? !isEventSeq(data["headerSeq"]) : Object.hasOwn(data, "headerSeq")) throw new Error(`${subject} requires headerSeq exactly when tool additions are present`);
			}
		}
	}
	if (event.type === "request/header") {
		if (!isRecord(data)) throw new Error(`${subject} data must be an object`);
		const header = data["header"];
		if (!isRecord(header)) throw new Error(`${subject} header must be an object`);
		if (Object.hasOwn(header, "system")) throw new Error(`${subject} must omit header.system; use system/message`);
		if (Array.isArray(header["tools"]) && header["tools"].length === 0) throw new Error(`${subject} must omit empty tools`);
		const defaults = header["adapterDefaults"];
		if (isRecord(defaults) && Object.keys(defaults).length === 0) throw new Error(`${subject} must omit empty adapterDefaults`);
	} else if (event.type === "tool/result") {
		if (!isRecord(data)) throw new Error(`${subject} data must be an object`);
		if (data["error"] === void 0) return;
		const message = data["message"];
		if (!isRecord(message) || message["isError"] !== true) throw new Error(`${subject} error requires message.isError === true`);
	}
}
/** Create an empty surface fold state. */
function createFoldState() {
	return {
		nodes: [],
		replaceGeneration: 0,
		contentGeneration: 0,
		projectedMessages: /* @__PURE__ */ new Map(),
		projections: /* @__PURE__ */ new Set()
	};
}
/** Whether a runtime value is a non-negative safe event sequence. */
function isEventSeq(value) {
	return typeof value === "number" && Number.isSafeInteger(value) && value >= 0 && !Object.is(value, -0);
}
/** Whether a runtime value is the exact positional-replacement shape. */
function isReplaceOp(value) {
	const op = value;
	return Object.keys(op).length === 3 && Object.hasOwn(op, "op") && Object.hasOwn(op, "startSeq") && Object.hasOwn(op, "endSeq") && op["op"] === "replace" && isEventSeq(op["startSeq"]) && isEventSeq(op["endSeq"]);
}
/** Validate event-local surface eligibility and return its operation. */
function surfaceOpOf(event) {
	const raw = event;
	if (!isSurfaceEligibleType(event.type)) {
		if (!KNOWN_SESSION_EVENT_TYPES.has(event.type) && event.ignorable === true) return;
		if (raw.surfaceOp !== void 0) throw new Error(`session event "${event.type}" is not surface-eligible and cannot carry surfaceOp`);
		if (raw.sourceEventSeqs !== void 0) throw new Error(`session event "${event.type}" is not surface-eligible and cannot carry sourceEventSeqs`);
		return;
	}
	const op = raw.surfaceOp;
	if (op === void 0) throw new Error(`session event "${event.type}" is surface-eligible and requires a surfaceOp marker`);
	if (op === "append") return op;
	if (op === null || typeof op !== "object" || Array.isArray(op)) throw new Error(`session event "${event.type}" carries an invalid surfaceOp`);
	if (!isReplaceOp(op)) throw new Error(`session event "${event.type}" carries an invalid replace surfaceOp`);
	return op;
}
/** Validate cited source-event seqs against prior log entries and the replacement range. */
function assertSourceEventReferences(event, shadowedSeqs) {
	const raw = event.sourceEventSeqs;
	if (event.type === "assistant/message" && raw !== void 0) throw new Error("assistant/message embeds its source stream and cannot carry sourceEventSeqs");
	const sources = /* @__PURE__ */ new Set();
	if (raw !== void 0) {
		if (!Array.isArray(raw)) throw new Error(`sourceEventSeqs on event at seq ${event.seq} must be an array when present`);
		if (raw.length === 0) throw new Error("sourceEventSeqs must not be empty");
		let nonEarlierSource;
		for (const source of raw) {
			if (!isEventSeq(source)) throw new Error(`session event "${event.type}" sourceEventSeqs must densely contain non-negative safe integers`);
			sources.add(source);
			if (nonEarlierSource === void 0 && source >= event.seq) nonEarlierSource = source;
		}
		if (sources.size !== raw.length) throw new Error("sourceEventSeqs must not contain duplicates");
		if (nonEarlierSource !== void 0) throw new Error(`sourceEventSeqs must reference earlier events: ${nonEarlierSource} >= current seq ${event.seq}`);
	}
	const missing = shadowedSeqs.filter((seq) => !sources.has(seq));
	if (missing.length > 0) throw new Error(`surface replace: sourceEventSeqs must include every shadowed surface node; missing ${missing.join(", ")}`);
}
/** Resolve tool additions against their immutable historical request header. */
function assertDeveloperHeader(event, events, baseSeq) {
	if (event.type !== "developer/message") return;
	validateSessionEventData(event, `developer/message at seq ${event.seq}`);
	if (event.data.headerSeq === void 0) return;
	const headerSeq = event.data.headerSeq;
	const headerEvent = events[headerSeq - baseSeq];
	if (headerSeq >= event.seq || headerEvent?.type !== "request/header") throw new Error("developer/message headerSeq must reference an earlier request/header");
	for (const block of event.data.message.content) {
		if (block.type !== "tool-addition") continue;
		const definitions = headerEvent.data.header.tools?.filter((tool) => tool.name === block.toolName) ?? [];
		if (definitions.length !== 1) throw new Error(`developer/message tool-addition "${block.toolName}" must name exactly one tool in headerSeq ${headerSeq}`);
		const definition = definitions[0];
		if (typeof definition.description !== "string" || !isRecord(definition.parameters)) throw new Error(`developer/message tool-addition "${block.toolName}" requires a complete tool definition in headerSeq ${headerSeq}`);
		if (Object.hasOwn(definition, "deferLoading") && definition.deferLoading !== true) throw new Error("developer/message referenced tool deferLoading must be true when present");
	}
}
/**
* Validate one event's surface metadata without checking membership in a log or surface.
* @param event - event whose marker and source sequence values are inspected.
* Unknown ignorable records retain opaque metadata and never change the surface.
* @returns the validated operation, or undefined for a log-only or unknown ignorable event.
* @throws when metadata violates event-local eligibility, marker, or source-sequence rules.
*/
function validateSurfaceMetadata(event) {
	const op = surfaceOpOf(event);
	if (op !== void 0 && op !== "append" && (op.startSeq >= event.seq || op.endSeq >= event.seq)) throw new Error(`surface replace at seq ${event.seq}: startSeq and endSeq must reference earlier events`);
	if (op !== void 0) assertSourceEventReferences(event, []);
	return op;
}
/** Locate one replacement range without mutating the current fold state. */
function replacementRange(state, op) {
	const startIdx = state.nodes.indexOf(op.startSeq);
	if (startIdx === -1) throw new Error(`surface replace: start seq ${op.startSeq} not found in surface`);
	const endIdx = state.nodes.indexOf(op.endSeq);
	if (endIdx === -1) throw new Error(`surface replace: end seq ${op.endSeq} not found in surface`);
	if (startIdx > endIdx) throw new Error(`surface replace: start seq ${op.startSeq} (index ${startIdx}) is after end seq ${op.endSeq} (index ${endIdx})`);
	return {
		startIdx,
		endIdx,
		shadowedSeqs: state.nodes.slice(startIdx, endIdx + 1)
	};
}
/**
* Deep structural equality over the session-event JSON value domain
* (null/boolean/number/string, arrays, plain objects). Replaces
* `node:util`'s isDeepStrictEqual to keep this module browser-safe.
*/
function isDeepEqualJson(a, b) {
	if (a === b) return true;
	if (Array.isArray(a) || Array.isArray(b)) {
		if (!Array.isArray(a) || !Array.isArray(b) || a.length !== b.length) return false;
		return a.every((item, i) => isDeepEqualJson(item, b[i]));
	}
	if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) return false;
	const aKeys = Object.keys(a);
	const bRecord = b;
	if (aKeys.length !== Object.keys(b).length) return false;
	return aKeys.every((key) => Object.hasOwn(b, key) && isDeepEqualJson(a[key], bRecord[key]));
}
/** Restrict a tool-result replacement to one current result's content. */
function assertToolResultRewrite(event, shadowedSeqs, events, baseSeq) {
	if (event.type !== "tool/result") return;
	if (shadowedSeqs.length !== 1) throw new Error("tool/result surface replacement must rewrite exactly one current node");
	for (const originalSeq of shadowedSeqs) {
		const original = events[originalSeq - baseSeq];
		if (original?.type !== "tool/result") throw new Error("tool/result surface replacement must target a current tool/result");
		const originalRest = { ...original.data };
		const replacementRest = { ...event.data };
		originalRest["message"] = {
			...original.data.message,
			content: null
		};
		replacementRest["message"] = {
			...event.data.message,
			content: null
		};
		if (!isDeepEqualJson(originalRest, replacementRest)) throw new Error("tool/result surface replacement may change only content");
	}
}
/**
* Protect the system prompt at surface node 0. A replacement covering node 0
* while that node is a `system/message` must itself be a `system/message` over
* exactly that node; later system nodes carry no protection and a compaction
* range may shadow them.
*/
function assertSystemHeadRewrite(event, state, startIdx, shadowedSeqs, events, baseSeq) {
	if (startIdx !== 0) return;
	if (events[state.nodes[0] - baseSeq]?.type !== "system/message") return;
	if (event.type !== "system/message" || shadowedSeqs.length !== 1) throw new Error("surface replace: node 0 holds the system prompt and may be rewritten only by a system/message over exactly that node");
}
/** Validate one event at its replay boundary and prepare its atomic fold transition. */
function planSurfaceEvent(state, event, expectedSeq, events, baseSeq, projections) {
	if (event.seq !== expectedSeq) throw new Error(`session event seq ${event.seq} is not contiguous; expected ${expectedSeq}`);
	const surfaceOp = validateSurfaceMetadata(event);
	assertDeveloperHeader(event, events, baseSeq);
	const projection = projections.find((item) => item.type === event.type);
	if (projection !== void 0) return {
		kind: "project",
		projection,
		messages: projection.project(event, {
			nodes: state.nodes,
			events,
			baseSeq,
			messages: state.projectedMessages
		})
	};
	if (MESSAGE_PROJECTION_EVENT_TYPES.has(event.type)) throw new Error(`session event "${event.type}" requires a message projection; load its owning plugin or supply its projection definition`);
	if (surfaceOp === void 0) return;
	if (surfaceOp === "append") return {
		kind: "append",
		seq: event.seq
	};
	const range = replacementRange(state, surfaceOp);
	assertSourceEventReferences(event, range.shadowedSeqs);
	assertToolResultRewrite(event, range.shadowedSeqs, events, baseSeq);
	assertSystemHeadRewrite(event, state, range.startIdx, range.shadowedSeqs, events, baseSeq);
	return {
		kind: "replace",
		seq: event.seq,
		start: surfaceOp.startSeq,
		end: surfaceOp.endSeq,
		...range
	};
}
/** Apply one event and return replacement metadata only when one occurred. */
function applySurfaceEvent(state, event, expectedSeq, events, baseSeq, projections) {
	return applySurfacePlan(state, planSurfaceEvent(state, event, expectedSeq, events, baseSeq, projections));
}
/** Commit one previously validated surface transition. */
function applySurfacePlan(state, plan) {
	if (plan?.kind === "append") state.nodes.push(plan.seq);
	else if (plan?.kind === "replace") {
		state.nodes.splice(plan.startIdx, plan.endIdx - plan.startIdx + 1, plan.seq);
		state.replaceGeneration += 1;
		state.contentGeneration += 1;
	} else if (plan?.kind === "project") {
		for (const [seq, message] of plan.messages) state.projectedMessages.set(seq, message);
		state.projections.add(plan.projection);
		state.contentGeneration += 1;
	}
	if (plan?.kind !== "replace") return;
	return {
		seq: plan.seq,
		start: plan.start,
		end: plan.end,
		shadowedSeqs: plan.shadowedSeqs
	};
}
/**
* Replay a complete session log through the canonical surface fold.
* @param events - session events in contiguous seq order.
* @param projections - pure interpreters for plugin-owned message changes; required definitions must be supplied.
* @returns detached current sequences and replacement history.
* @throws when an interpreter is missing or an event violates its projection, surface metadata, source attribution, or replacement rules.
*/
function foldSurface(events, projections = []) {
	const state = createFoldState();
	const replacements = [];
	for (const [index, event] of events.entries()) {
		const replacement = applySurfaceEvent(state, event, SessionSeq(index), events, SessionLogOffset(0), projections);
		if (replacement !== void 0) replacements.push(replacement);
	}
	return {
		nodes: [...state.nodes],
		replacements,
		projectedMessages: new Map(state.projectedMessages)
	};
}
/** Incremental ordered surface view and append-boundary validator. */
var SurfaceManager = class {
	log;
	baseSeq;
	projections;
	/** Shared transition state; replacement history is not retained. */
	_state = createFoldState();
	/** Last processed absolute seq. */
	_lastProcessedSeq;
	/** Candidate already validated by `validateNext`, pending exact log admission. */
	_pendingPlan;
	/**
	* @param log - Contiguous complete log or loaded event window.
	* @param baseSeq - Absolute sequence of the window's first event.
	* @param projections - live borrowed definitions; removing a used definition invalidates further reads.
	*/
	constructor(log, baseSeq = SessionLogOffset(0), projections = []) {
		this.log = log;
		this.baseSeq = baseSeq;
		this.projections = projections;
		this._lastProcessedSeq = baseSeq === 0 ? -1 : SessionSeq(baseSeq - 1);
	}
	/**
	* Validate the next candidate without mutating the committed surface.
	* @param event - candidate event that has not entered the log yet.
	*/
	validateNext(event) {
		this._assertProjections();
		if (this._lastProcessedSeq < this.baseSeq + this.log.length - 1) this._processDelta();
		const expectedSeq = SessionSeq(this.baseSeq + this.log.length);
		this._pendingPlan = {
			event,
			expectedSeq,
			plan: planSurfaceEvent(this._state, event, expectedSeq, this.log, this.baseSeq, this.projections)
		};
	}
	/** Monotonic count of folded positional replacements. */
	get replaceGeneration() {
		this._assertProjections();
		if (this._lastProcessedSeq < this.baseSeq + this.log.length - 1) this._processDelta();
		return this._state.replaceGeneration;
	}
	/** Monotonic count of committed changes to existing model-visible content. */
	get contentGeneration() {
		this._assertProjections();
		if (this._lastProcessedSeq < this.baseSeq + this.log.length - 1) this._processDelta();
		return this._state.contentGeneration;
	}
	/**
	* Project one message with every committed message projection applied.
	* @param event - message-producing or log-only event.
	* @returns its immutable projected message, or null when it produces none.
	*/
	deriveEventMessage(event) {
		this._assertProjections();
		if (this._lastProcessedSeq < this.baseSeq + this.log.length - 1) this._processDelta();
		return deriveEventMessage(event, this._state.projectedMessages);
	}
	/** Surface event sequences in model-visible order. */
	get nodes() {
		this._assertProjections();
		if (this._lastProcessedSeq < this.baseSeq + this.log.length - 1) this._processDelta();
		return this._state.nodes;
	}
	/** Fold events appended since the previous access. */
	_processDelta() {
		const tailSeq = this.baseSeq + this.log.length - 1;
		for (let seq = this._lastProcessedSeq + 1; seq <= tailSeq; seq++) {
			const index = seq - this.baseSeq;
			const event = this.log[index];
			const pending = this._pendingPlan;
			if (pending?.event === event && pending.expectedSeq === seq) applySurfacePlan(this._state, pending.plan);
			else applySurfaceEvent(this._state, event, SessionSeq(seq), this.log, this.baseSeq, this.projections);
			if (pending !== void 0 && pending.expectedSeq <= seq) this._pendingPlan = void 0;
			this._lastProcessedSeq = SessionSeq(seq);
		}
	}
	/** Cached messages cannot outlive the definitions that interpreted their log. */
	_assertProjections() {
		const candidate = this._pendingPlan;
		const pending = candidate !== void 0 && this.log[candidate.expectedSeq - this.baseSeq] === candidate.event ? candidate.plan : void 0;
		const required = pending?.kind === "project" ? [...this._state.projections, pending.projection] : this._state.projections;
		for (const projection of required) if (!this.projections.includes(projection)) throw new Error(`session message projection "${projection.type}" was removed or replaced; restore the session with its owning plugin`);
	}
};
//#endregion
//#region lib/types/request-header.js
/**
* Request-header reconstruction utilities over full `request/header` session
* events. Anyone holding a session log reconstructs the {@link EpochHeader}
* any request was built under by taking the latest canonical snapshot; the
* loop uses the same equality helper to avoid logging unchanged headers.
*
* @module dsh-session/request-header
*/
/**
* Normalize a header to canonical form: an empty tool list becomes an absent
* field, matching how requests are built. Logging, folding, and comparison use
* this one representation.
* @param header - the header to normalize (not mutated).
* @returns the canonical header.
*/
function canonicalHeader(header) {
	const adapterDefaults = header.adapterDefaults;
	return {
		config: header.config,
		...adapterDefaults?.reasoningEffort === true || adapterDefaults?.maxTokens === true ? { adapterDefaults } : {},
		...header.tools !== void 0 && header.tools.length > 0 ? { tools: header.tools } : {}
	};
}
/** Canonical JSON equality for tool schemas assembled through the same path. */
function sameSchema(a, b) {
	return JSON.stringify(a) === JSON.stringify(b);
}
/**
* Field-wise equality over canonical headers. Tool schemas compare in order.
* @param a - one canonical header.
* @param b - the other.
* @returns whether config, adapter defaults, and tools all match.
*/
function headerEquals(a, b) {
	if (!callConfigEquals(a.config, b.config) || a.adapterDefaults?.reasoningEffort !== b.adapterDefaults?.reasoningEffort || a.adapterDefaults?.maxTokens !== b.adapterDefaults?.maxTokens) return false;
	const at = a.tools ?? [];
	const bt = b.tools ?? [];
	return at.length === bt.length && at.every((tool, i) => sameSchema(tool, bt[i]));
}
/**
* Fold the header events of a log (or any prefix) into the
* {@link EpochHeader} in force after the last snapshot. Non-header events are
* skipped. This is the pure offline reconstruction path; the live session
* tracks the same fold incrementally.
* @param events - session events in log order.
* @param from - a previously folded state to continue from.
* @returns the latest canonical header, or undefined when none exists yet.
*/
function foldRequestHeader(events, from) {
	let state = from;
	for (const event of events) if (event.type === "request/header") state = canonicalHeader(event.data.header);
	return state;
}
//#endregion
//#region lib/types/tool-history.js
/** Stateful reconstruction of historical tool definitions for request projection. */
/** Folds committed headers and developer messages independently of model capability. */
var ToolHistoryProjection = class {
	/** Historical declarations indexed by the header sequence referenced by additions. */
	headers = /* @__PURE__ */ new Map();
	/** Definitions retained in the current declaration series, including removed tools. */
	declared = /* @__PURE__ */ new Map();
	/** Active definitions from the latest request header. */
	active = [];
	/** Active names reconstructed from the baseline and recorded updates. */
	available = /* @__PURE__ */ new Set();
	/** Header that starts the current declaration series; absent before the first header. */
	baselineSeq;
	/** Immutable request snapshot of the current baseline and resolved updates. */
	history = deepFreeze({
		tools: [],
		updates: []
	});
	/**
	* Consume the next committed event in log order.
	* @param event - a session event, including inherited events during restoration.
	*/
	apply(event) {
		if (event.type === "request/header") {
			const tools = event.data.header.tools ?? [];
			this.headers.set(event.seq, tools);
			const redeclared = tools.some((tool) => {
				const before = this.declared.get(tool.name);
				return before !== void 0 && JSON.stringify(before) !== JSON.stringify(tool);
			});
			if (this.baselineSeq === void 0 || event.data.reason === "series" || event.data.startsSeries || redeclared) {
				this.baselineSeq = event.seq;
				this.declared = new Map(tools.map((tool) => [tool.name, tool]));
				this.history = deepFreeze({
					tools,
					updates: []
				});
				this.available = new Set(tools.map((tool) => tool.name));
			}
			this.active = tools;
		} else if (event.type === "developer/message") {
			const { message, headerSeq } = event.data;
			const definitions = headerSeq === void 0 ? [] : this.headers.get(headerSeq);
			const additions = message.content.flatMap((block) => {
				if (block.type !== "tool-addition") return [];
				const tool = definitions?.find((tool) => tool.name === block.toolName);
				if (tool === void 0) throw new Error(`tool history: missing definition for ${block.toolName}`);
				return [tool];
			});
			for (const tool of additions) this.declared.set(tool.name, tool);
			for (const block of message.content) if (block.type === "tool-addition") this.available.add(block.toolName);
			else if (block.type === "tool-removal") this.available.delete(block.toolName);
			this.history = deepFreeze({
				tools: this.history.tools,
				updates: [...this.history.updates, {
					messageId: message.id,
					additions
				}]
			});
		}
	}
	/**
	* Read an immutable snapshot; subsequent events do not mutate it.
	* @returns initial declarations and historically resolved additions for the current series.
	*/
	snapshot() {
		if (this.active.length !== this.available.size || this.active.some((tool) => !this.available.has(tool.name))) return deepFreeze({
			tools: this.active,
			updates: []
		});
		return this.history;
	}
};
//#endregion
//#region lib/types/repair.js
/**
* Pending tool-result recovery shared by failed live steps, interrupted logs,
* and fork seeds. Tail repair preserves closed steps and supplies only missing
* tool results and lifecycle boundaries, with cause-specific retry guidance.
* @module @deepseek-ai/dsh-session/repair
*/
/** Recovery code for an assistant tool request that never reached a recorded call start. */
const TOOL_NOT_STARTED = "TOOL_NOT_STARTED";
/** Recovery code for a recorded tool call whose completed outcome was not durably recorded. */
const TOOL_OUTCOME_UNKNOWN = "TOOL_OUTCOME_UNKNOWN";
/** Model-visible wording of the synthetic error tool results, keyed by cause. */
const CLOSER_TEXT = {
	interrupted: {
		started: "The tool call was interrupted after it was recorded, but no result was durably recorded. Its outcome is unknown. Decide whether to retry from the tool semantics: retry only if the operation is read-only or idempotent; if it may have side effects, first verify external state or ask the user. Do not retry blindly.",
		notStarted: "The tool call was interrupted before the Harness recorded it as started. Retry it if it is still needed."
	},
	forked: {
		started: "The history inherited by this branch records this tool call starting but does not include its result. The parent session may have completed it after the fork point. Decide whether to retry from the tool semantics: retry only if the operation is read-only or idempotent; if it may have side effects, first verify external state or ask the user. Do not retry blindly.",
		notStarted: "The history inherited by this branch has no record of this tool call starting. The parent session may have executed it after the fork point. Decide whether to retry from the tool semantics: retry only if the operation is read-only or idempotent; if it may have side effects, first verify external state or ask the user. Do not retry blindly."
	}
};
/**
* Return deterministic synthetic events that close an open tail turn. Unmatched
* calls receive error results first, followed by an open `step/end` and a
* cause-specific `turn/end`; sequences continue the log and timestamps reuse the
* last real event. A balanced or empty log returns no events.
*
* @param events - the loaded durable log to scan (a valid committed prefix, possibly with a crash tail).
* @param cause - the owning close operation: selects result wording and the turn-ending reason.
* @returns the synthetic closer events to append after `events`, in order; empty when the log is already balanced.
*/
function openTurnClosers(events, cause) {
	let openTurn = null;
	let openStep = null;
	const recovery = new ToolCallRecovery(cause);
	for (const event of events) {
		recovery.observe(event);
		switch (event.type) {
			case "turn/start":
				openTurn = event.data.turn;
				openStep = null;
				break;
			case "turn/end":
				openTurn = null;
				openStep = null;
				break;
			case "step/start":
				openStep = event.data.step;
				break;
			case "step/end":
				openStep = null;
				break;
			default: break;
		}
	}
	const last = events.at(-1);
	if (openTurn === null || last === void 0) return [];
	const closers = recovery.results();
	let seq = last.seq + closers.length + 1;
	const time = last.time;
	if (openStep !== null) closers.push({
		type: "step/end",
		seq: SessionSeq(seq++),
		time,
		data: {
			turn: openTurn,
			step: openStep
		}
	});
	closers.push({
		type: "turn/end",
		seq: SessionSeq(seq++),
		time,
		data: {
			turn: openTurn,
			reason: { kind: cause.kind }
		}
	});
	return closers;
}
/**
* Track unanswered assistant tool requests from one Session's committed events.
* Observe from the start of the owned step or replay prefix, and recover before
* its step closes. This state retains pending identities, not event history.
*/
var ToolCallRecovery = class {
	cause;
	pendingCalls = /* @__PURE__ */ new Map();
	last;
	/** @param cause - defaults to interrupted live/crash recovery; fork-seed construction supplies its own cause. */
	constructor(cause = { kind: "interrupted" }) {
		this.cause = cause;
	}
	/**
	* Consume the next committed event; closed steps and turn boundaries discard pending requests.
	* @param event - the next event from the same Session, in sequence order.
	*/
	observe(event) {
		this.last = {
			seq: event.seq,
			time: event.time
		};
		switch (event.type) {
			case "turn/start":
			case "turn/end":
			case "step/end":
				this.pendingCalls.clear();
				break;
			case "assistant/message":
				for (const block of event.data.message.content) if (block.type === "tool-call") this.pendingCalls.set(block.id, {
					turn: event.data.turn,
					step: event.data.step
				});
				break;
			case "tool/call": {
				const entry = this.pendingCalls.get(event.data.callId);
				if (entry) entry.callSeq = event.seq;
				break;
			}
			case "tool/result": {
				const callId = event.data.message.source.callId;
				const entry = this.pendingCalls.get(callId);
				if (event.surfaceOp === "append" && entry !== void 0 && entry.turn === event.data.turn && entry.step === event.data.step) this.pendingCalls.delete(callId);
				break;
			}
			default: break;
		}
	}
	/**
	* Build conservative error results in assistant order without changing tracked state.
	* Sequences follow the latest observed event and timestamps reuse its time.
	* Callers commit the results and observe those commits before recovering again.
	* @returns pending tool-result events, empty when no request remains unanswered.
	*/
	results() {
		if (this.last === void 0) return [];
		let seq = this.last.seq + 1;
		const time = this.last.time;
		const results = [];
		const text = CLOSER_TEXT[this.cause.kind];
		for (const [callId, { turn, step, callSeq }] of this.pendingCalls) {
			const started = callSeq !== void 0;
			const message = deepFreeze({
				id: brandString(`${this.cause.kind}-tool-result-${callId}-${seq}`),
				role: "tool",
				toolCallId: callId,
				isError: true,
				source: {
					kind: "tool",
					callId
				},
				content: [{
					type: "text",
					text: started ? text.started : text.notStarted
				}]
			});
			results.push({
				type: "tool/result",
				seq: SessionSeq(seq++),
				time,
				data: {
					turn,
					step,
					message,
					error: started ? {
						name: "ToolOutcomeUnknownError",
						code: TOOL_OUTCOME_UNKNOWN
					} : {
						name: "ToolNotStartedError",
						code: TOOL_NOT_STARTED
					}
				},
				surfaceOp: "append",
				...started ? { sourceEventSeqs: [callSeq] } : {}
			});
		}
		return results;
	}
};
/**
* Crash-recovery entry point: synthetic closers that balance a persisted log
* whose tail turn was interrupted. Used by crash-recovery callers; fork
* seeds receive their `forked`-cause closers through `buildForkSeed` in
* `./fork.ts`.
*
* @param events - the persisted log to scan, possibly ending inside an open turn.
* @returns the synthetic `interrupted` closer events to append after `events`; empty when the log is already balanced.
*/
function interruptedTurnClosers(events) {
	return openTurnClosers(events, { kind: "interrupted" });
}
//#endregion
//#region lib/types/fork.js
/**
* Fork seed construction over an exact source-event prefix.
* @module @deepseek-ai/dsh-session/fork
*/
/**
* Copy an inclusive event prefix, mark its inherited cut, and close its open tail with forked results
* and step/turn endings. Closed steps and turns are preserved unchanged.
* The caller validates that the boundary is an existing contiguous event seq;
* Session construction snapshots the borrowed events before publication.
*
* @param events - source log with contiguous seqs from zero.
* @param boundary - inclusive source event seq the child inherits through.
* @returns a new array retaining the source event objects, followed by synthetic
*   closers outside the inherited prefix counted by `inheritedEventCount`.
*/
function buildForkSeed(events, boundary) {
	const prefix = events.slice(0, boundary + 1);
	prefix.push({
		type: "session/end-seed",
		seq: SessionSeq(boundary + 1),
		time: events[boundary].time,
		data: { inherited: true }
	});
	return prefix.concat(openTurnClosers(prefix, { kind: "forked" }));
}
//#endregion
//#region lib/types/preparation.js
/**
* Ownership of one unpublished Session before registry publication.
* @module @deepseek-ai/dsh-session/preparation
*/
/**
* One exact unpublished Session and the provider state that keeps it usable.
* Disposal is synchronous and idempotent. Providers decide whether release
* returns the Session to a cache or discards it; publication may consume that
* state before disposal, making the callback a no-op.
*/
var SessionPreparation = class SessionPreparation {
	options;
	released = false;
	/** The exact Session to use for setup and publication. */
	session;
	constructor(session, options) {
		this.options = options;
		this.session = session;
	}
	/**
	* Wrap an unpublished Session in one preparation lifetime.
	* @param session - exact unpublished Session.
	* @param options - optional provider release behavior.
	* @returns a preparation disposed after publication or rollback.
	*/
	static create(session, options) {
		return new SessionPreparation(session, options ?? {});
	}
	/** Release provider state once when this preparation leaves its caller. */
	[Symbol.dispose]() {
		if (this.released) return;
		this.released = true;
		this.options.release?.();
	}
};
//#endregion
//#region lib/types/seq-ranges.js
/** Lossless range encoding for JSONL `sourceEventSeqs` arrays. */
function isStrictlyIncreasing(values) {
	return values.every((value, index) => index === 0 || value > values[index - 1]);
}
/**
* Replace profitable consecutive runs with inclusive pairs.
* @param values - validated in-memory source sequences.
* @returns a lossless JSON storage form.
*/
function encodeSeqRanges(values) {
	if (!isStrictlyIncreasing(values)) return [...values];
	const encoded = [];
	for (let start = 0; start < values.length;) {
		let end = start;
		while (end + 1 < values.length && values[end + 1] === values[end] + 1) end += 1;
		if (end - start >= 2) encoded.push([values[start], values[end]]);
		else for (let index = start; index <= end; index += 1) encoded.push(values[index]);
		start = end + 1;
	}
	return encoded;
}
/**
* Expand a JSON storage-form source sequence array.
* @param value - parsed storage value.
* @param maxEntries - largest list permitted by the owning event.
* @returns the in-memory source sequences.
*/
function decodeSeqRanges(value, maxEntries = Number.MAX_SAFE_INTEGER) {
	if (!Array.isArray(value)) throw new TypeError("sourceEventSeqs must be an array");
	const decoded = [];
	let hasRange = false;
	for (const entry of value) {
		if (typeof entry === "number") {
			assertSeq(entry);
			if (decoded.length >= maxEntries) throw new TypeError("sourceEventSeqs exceeds its event sequence");
			decoded.push(SessionSeq(entry));
			continue;
		}
		if (!Array.isArray(entry) || entry.length !== 2) throw new TypeError("sourceEventSeqs range entries must be [start, end] pairs");
		const start = entry[0];
		const end = entry[1];
		assertSeq(start);
		assertSeq(end);
		if (end < start) throw new TypeError("sourceEventSeqs ranges require start <= end");
		if (end - start + 1 > maxEntries - decoded.length) throw new TypeError("sourceEventSeqs range exceeds its event sequence");
		for (let seq = start; seq <= end; seq += 1) decoded.push(SessionSeq(seq));
		hasRange = true;
	}
	if (hasRange && !isStrictlyIncreasing(decoded)) throw new TypeError("sourceEventSeqs ranges must be strictly increasing");
	return decoded;
}
function assertSeq(value) {
	if (!Number.isSafeInteger(value) || value < 0) throw new TypeError("sourceEventSeqs must contain non-negative safe integers");
}
//#endregion
//#region lib/types/index.js
/**
* Event-sourced session service: append-only session log, in-memory store, and
* the derived LLM message history. Persistence is a plugin concern (subscribe
* to `session/event`, drain on `session/flush`).
*
* @module @deepseek-ai/dsh-session
*/
/** Validate and freeze one detached creation header in place. */
function validateSessionHeader(id, input) {
	if (input === null || typeof input !== "object" || Array.isArray(input)) throw new Error("session header is not a plain JSON record");
	const record = input;
	if (Object.hasOwn(record, "seedLength")) throw new Error("session header has invalid field \"seedLength\"");
	if (record.version !== 4) throw new Error(`session header version must be 4, got ${String(record.version)}`);
	if (record.id !== id) throw new Error(`session header id "${String(record.id)}" does not match session id "${id}"`);
	if (typeof record.createdAt !== "number" || !Number.isSafeInteger(record.createdAt) || record.createdAt < 0) throw new Error("session header createdAt must be a non-negative safe integer");
	if (record.cwd !== void 0) {
		if (typeof record.cwd !== "string") throw new Error("session header cwd must be a string");
		if (!isAbsolute(record.cwd)) throw new Error(`session header cwd must be an absolute path, got "${record.cwd}"`);
	}
	if (record.parentSession !== void 0 && typeof record.parentSession !== "string") throw new Error("session header parentSession must be a string");
	if (typeof record.isSeeded !== "boolean") throw new Error("session header isSeeded must be a boolean");
	if (record.origin !== void 0 && record.origin !== "subagent") throw new Error("session header origin must be \"subagent\"");
	if (record.delegationDepth !== void 0 && (typeof record.delegationDepth !== "number" || !Number.isSafeInteger(record.delegationDepth) || record.delegationDepth < 0)) throw new Error("session header delegationDepth must be a non-negative safe integer");
	if (record.agentPreset !== void 0 && typeof record.agentPreset !== "string") throw new Error("session header agentPreset must be a string");
	return deepFreeze(record);
}
/** Validate and freeze one exclusively owned persistence header in place. */
function validateRestoredSessionHeader(id, input) {
	if (input !== null && typeof input === "object" && !Array.isArray(input)) {
		const prototype = Reflect.getPrototypeOf(input);
		if (prototype !== Object.prototype && prototype !== null) throw new Error("session header is not a plain JSON record");
	}
	return validateSessionHeader(id, input);
}
/** Detach, validate, and freeze the creation metadata published by a session. */
function snapshotSessionHeader(id, source) {
	const snapshot = snapshotJsonValue(source === void 0 ? {
		version: 4,
		id,
		createdAt: Date.now(),
		isSeeded: false
	} : source);
	if (snapshot === void 0) throw new Error("session header is not losslessly JSON-serializable");
	return validateSessionHeader(id, snapshot);
}
/**
* Validate an exclusively owned event and deeply freeze its identified message
* without copying the event. The caller transfers an object graph that no
* producer retains and that shares no mutable children with another event.
* Use {@link snapshotSessionEvent} when exclusive ownership is not guaranteed.
* @param event - exclusively owned event imported across a trusted boundary.
* @returns the same event object with a validated, deeply frozen message.
* @throws when event-local surface metadata, request-header fields, or message invariants are invalid; history relations are not checked.
*/
function adoptSessionEvent(event) {
	validateSessionEventData(event, `session event at seq ${event.seq}`);
	validateSurfaceMetadata(event);
	assertMessageEventShape(event, `session event at seq ${event.seq}`);
	switch (event.type) {
		case "user/message":
			deepFreeze(event.data);
			break;
		case "developer/message":
		case "system/message":
		case "assistant/message":
		case "tool/result":
			deepFreeze(event.data.message);
			break;
		default: break;
	}
	return event;
}
/**
* Detach one event while preserving deep immutability for its identified message.
* @param event - event imported across a query or persistence boundary.
* @returns a detached event snapshot with a validated, deeply frozen message.
*/
function snapshotSessionEvent(event) {
	return adoptSessionEvent(structuredClone(event));
}
/** Validate the fixed event envelope after one-pass JSON materialization. */
function assertSessionEventEnvelope(value, index) {
	if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error(`seed event at index ${index} has an invalid event envelope`);
	const event = value;
	for (const key in event) switch (key) {
		case "type":
		case "seq":
		case "time":
		case "data":
		case "surfaceOp":
		case "sourceEventSeqs":
		case "ignorable": break;
		default: throw new Error(`seed event at index ${index} has an invalid event envelope`);
	}
	const type = event["type"];
	const seq = event["seq"];
	const time = event["time"];
	if (typeof type !== "string" || typeof seq !== "number" || !Number.isSafeInteger(seq) || seq < 0 || Object.is(seq, -0) || typeof time !== "number" || !Number.isSafeInteger(time) || event["data"] === void 0 || event["ignorable"] !== void 0 && event["ignorable"] !== true) throw new Error(`seed event at index ${index} has an invalid event envelope`);
	validateSessionEventData(event, `seed ${type} at index ${index}`);
	switch (type) {
		case "request/header":
		case "developer/message":
		case "system/message":
		case "user/message":
		case "assistant/attempt":
		case "assistant/message":
		case "tool/result":
			assertCurrentLlmShape(event, index);
			break;
	}
}
/** Reject obsolete request headers and malformed messages at the seed/load boundary. */
function assertCurrentLlmShape(event, index) {
	const data = event["data"];
	const record = typeof data === "object" && data !== null ? data : void 0;
	if (event["type"] === "request/header") {
		const headerRecord = record?.["header"];
		const config = headerRecord["config"];
		if (!hasProviderModel(config)) throw new Error(`seed request/header at index ${index} lacks provider/model`);
		const configRecord = config;
		const reasoningEffort = configRecord["reasoningEffort"];
		if (reasoningEffort !== void 0 && (typeof reasoningEffort !== "string" || reasoningEffort.length === 0)) throw new Error(`seed request/header at index ${index} has an invalid reasoningEffort`);
		assertAdapterDefaults(headerRecord["adapterDefaults"], configRecord, index);
		const reason = record?.["reason"];
		if (reason !== "initial" && reason !== "resume" && reason !== "change" && reason !== "series") throw new Error(`seed request/header at index ${index} has an invalid reason`);
		if (record?.["startsSeries"] !== void 0 && record["startsSeries"] !== true) throw new Error(`seed request/header at index ${index} has an invalid startsSeries marker`);
	}
	const type = event["type"];
	if (type === "assistant/attempt") {
		assertAssistantSettlementShape(record, type, index);
		return;
	}
	if (!isMessageEventType(type)) return;
	assertMessageEventShape(event, `seed ${type} at index ${index}`);
	if (type === "assistant/message") assertAssistantSettlementShape(record, type, index);
}
/** Validate fields used directly by restored Session lifecycle logic without replaying the embedded stream. */
function assertAssistantSettlementShape(data, type, index) {
	const turn = data?.["turn"];
	const step = data?.["step"];
	if (typeof turn !== "number" || !Number.isSafeInteger(turn) || turn < 0 || Object.is(turn, -0) || typeof step !== "number" || !Number.isSafeInteger(step) || step < 0 || Object.is(step, -0) || !Array.isArray(data?.["stream"])) throw new Error(`seed ${type} at index ${index} has invalid settlement fields`);
}
const allowedAdapterKeys = new Set(["reasoningEffort", "maxTokens"]);
/** Validate adapter-default markers imported from a durable request header. */
function assertAdapterDefaults(value, config, index) {
	if (value === void 0) return;
	if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(`seed request/header at index ${index} has invalid adapterDefaults`);
	const defaults = value;
	if (Object.keys(defaults).some((key) => !allowedAdapterKeys.has(key)) || Object.values(defaults).some((marker) => marker !== true) || defaults["reasoningEffort"] === true && config["reasoningEffort"] === void 0 || defaults["maxTokens"] === true && config["maxTokens"] === void 0) throw new Error(`seed request/header at index ${index} has invalid adapterDefaults`);
}
/** The surface event types whose payload carries an identified message. */
function isMessageEventType(type) {
	return type === "developer/message" || type === "system/message" || type === "user/message" || type === "assistant/message" || type === "tool/result";
}
const MESSAGE_ROLE_BY_TYPE = {
	"system/message": "system",
	"developer/message": "developer",
	"user/message": "user",
	"assistant/message": "assistant",
	"tool/result": "tool"
};
/** Validate only the event-specific invariants needed to safely replay a message. */
function assertMessageEventShape(event, subject) {
	const type = event["type"];
	if (!isMessageEventType(type)) return;
	const data = event["data"];
	const record = typeof data === "object" && data !== null ? data : void 0;
	const message = type === "user/message" ? record : record?.["message"];
	if (typeof message !== "object" || message === null || typeof message["id"] !== "string" || message["id"] === "") throw new Error(`${subject} lacks an identified message`);
	const messageRecord = message;
	const expectedRole = MESSAGE_ROLE_BY_TYPE[type];
	if (messageRecord["role"] !== expectedRole) throw new Error(`${subject} message must have role "${expectedRole}"`);
	const source = messageRecord["source"];
	if (typeof source !== "object" || source === null || typeof source["kind"] !== "string" || source["kind"] === "") throw new Error(`${subject} message has invalid source`);
	if (!Array.isArray(messageRecord["content"])) throw new Error(`${subject} message has invalid content`);
	const sourceRecord = source;
	if (type === "system/message") {
		if (sourceRecord["kind"] !== "system-prompt") throw new Error(`${subject} message must have system-prompt source`);
		return;
	}
	if (type === "assistant/message") {
		if (sourceRecord["kind"] !== "model" || !hasProviderModel(sourceRecord)) throw new Error(`${subject} message must have model source`);
		return;
	}
	if (type !== "tool/result") return;
	if (sourceRecord["kind"] !== "tool" || typeof sourceRecord["callId"] !== "string" || sourceRecord["callId"] === "") throw new Error(`${subject} message must have tool source`);
	if (messageRecord["toolCallId"] !== sourceRecord["callId"]) throw new Error(`${subject} message has mismatched tool call ids`);
}
/** Whether an unknown value carries the current provider/model pair. */
function hasProviderModel(value) {
	if (typeof value !== "object" || value === null) return false;
	const pair = value;
	return typeof pair["provider"] === "string" && pair["provider"].length > 0 && typeof pair["model"] === "string" && pair["model"].length > 0;
}
/** Resolve one listener snapshot, including Cordis's internal dispatch checks. */
function collectSessionCallbacks(ctx, args) {
	return [...ctx.events.dispatch("emit", args)];
}
/** Invoke one resolved observe-only listener snapshot with per-listener containment. */
function invokeContainedSessionObservers(ctx, name, id, args, callbacks) {
	for (const callback of callbacks) try {
		const returned = callback(...args);
		Promise.resolve(returned).catch((error) => {
			ctx.logger.warn(`session "${id}": ${name} listener rejected: ${String(error)}`);
		});
	} catch (error) {
		ctx.logger.warn(`session "${id}": ${name} listener threw: ${String(error)}`);
	}
}
/** Store attachment for the append path; module-private to keep Session store-agnostic publicly. */
const attachments = /* @__PURE__ */ new WeakMap();
/**
* An event-sourced session: an append-only log of {@link SessionEvent}s.
*
* Plain class (not a Service) — create live instances via
* `ctx.sessions.create()` and detached instances via {@link create}.
* Seeding with an existing event log replays/forks a session.
* @typert object
*/
var Session = class Session {
	log = [];
	/** Single incremental owner of surface acceptance and projection state. */
	surfaceManager;
	/** The ordered surface over this session's event log. */
	get surface() {
		return this.surfaceManager;
	}
	/**
	* Detached, deep-frozen creation metadata (format version, cwd, lineage,
	* and whether fork history exists). Supplied by the store via `ctx.sessions.create()`. When a
	* `Session` is created without a store-owned header, a minimal header is
	* synthesized (stamped with the current {@link SESSION_FORMAT_VERSION}) so
	* `session.header` is always present. Kept out of the event log — it is a
	* storage concern, not replayable conversation state.
	*/
	header;
	/** Number of leading events inherited from this Session's fork parent. */
	inheritedEventCount;
	/** The session identity, derived from its durable header's single copy. */
	get id() {
		return this.header.id;
	}
	/**
	* The constructor seed length (0 without one), before any marker appended
	* during construction. Seed events never publish on `session/event`. A
	* marker appended before the store attaches occupies this seq without
	* publishing either; otherwise this seq is available for the next append.
	*
	* This in-process offset is not persisted. A fork seed can already contain
	* the child's inherited marker and synthetic closers, so its child-owned
	* history starts at {@link inheritedEventCount}, before this offset. A
	* resumed Session's seed contains its full stored log, while its inherited
	* count keeps the durable fork cut. Consumers needing complete canonical
	* history start at seq 0.
	*/
	firstLiveSeq;
	/**
	* First event produced for this object lifecycle. A new fork includes its
	* child-owned seed marker and closers; a restored Session starts after its
	* complete stored prefix. This in-process capture offset is not persisted.
	*/
	firstLifecycleSeq;
	/**
	* Create a detached session by validating and snapshotting borrowed seed
	* events and storage metadata.
	* @param id - session identity.
	* @param seed - optional borrowed replay or fork events.
	* @param header - optional borrowed storage metadata.
	* @param inheritedEventCount - exact fork-inherited prefix length for a seeded header.
	* @param projections - pure interpreters for plugin-owned message changes.
	* @returns a detached session.
	* @throws when a seed event requires a missing message interpreter or fails validation.
	*/
	static create(id, seed, header, inheritedEventCount, projections) {
		return new Session(id, seed, header, "snapshot", inheritedEventCount, projections);
	}
	/**
	* Restore a detached session by adopting an independently owned or deeply frozen seed.
	* Runtime-required event fields, event envelopes, sequence continuity, surface
	* transitions, and header fields are validated without copying or freezing events.
	* Embedded Assistant streams remain opaque until a stream consumer or storage
	* verifier reads them.
	* @param id - restored session identity.
	* @param seed - independently owned or deeply frozen events.
	* @param header - independently owned storage metadata.
	* @param inheritedEventCount - exact fork-inherited prefix length decoded from storage.
	* @param eventState - aliasing state carried from the operation that produced the seed.
	* @param projections - pure interpreters for plugin-owned message changes.
	* @returns a restored detached session.
	* @throws when a seed event requires a missing message interpreter or fails validation.
	*/
	static fromRestore(id, seed, header, inheritedEventCount, eventState, projections) {
		return new Session(id, seed, header, eventState, inheritedEventCount, projections);
	}
	constructor(id, seed, header, mode = "snapshot", suppliedInheritedEventCount, projections = []) {
		this.surfaceManager = new SurfaceManager(this.log, SessionLogOffset(0), projections);
		const restoredHeader = mode === "snapshot" ? void 0 : validateRestoredSessionHeader(id, header);
		if (seed !== void 0) for (const [index, source] of seed.entries()) {
			const snapshot = mode === "snapshot" ? snapshotJsonValue(source) : source;
			if (snapshot === void 0) throw new Error(`seed event at index ${index} is not losslessly JSON-serializable`);
			assertSessionEventEnvelope(snapshot, index);
			if (snapshot.seq !== index) throw new Error(`seed event at index ${index} has seq ${snapshot.seq} (expected ${index}); seed must be contiguous from 0`);
			try {
				this.surfaceManager.validateNext(snapshot);
			} catch (error) {
				throw new Error(`invalid seed event at index ${index}: ${error instanceof Error ? error.message : "invalid surface metadata"}`);
			}
			this.log.push(mode === "snapshot" ? deepFreeze(snapshot) : snapshot);
		}
		this.firstLiveSeq = SessionLogOffset(this.log.length);
		this.header = restoredHeader ?? snapshotSessionHeader(id, header);
		if (this.header.isSeeded && seed === void 0) throw new Error("seeded session requires an explicit constructor seed");
		if (this.header.isSeeded && suppliedInheritedEventCount === void 0) throw new Error("seeded session requires an inherited event count");
		const inheritedEventCount = SessionLogOffset(suppliedInheritedEventCount ?? 0);
		if (!this.header.isSeeded && inheritedEventCount !== 0) throw new Error("unseeded session inherited event count must be 0");
		if (inheritedEventCount > this.log.length) throw new Error("session inherited event count exceeds its event log");
		const seedMarker = this.log[inheritedEventCount];
		const markedSeed = seedMarker?.type === "session/end-seed" && seedMarker.data.inherited === true;
		if (mode === "snapshot" && this.header.isSeeded && inheritedEventCount !== this.log.length && !markedSeed) throw new Error("seeded session constructor seed must equal its inherited prefix or mark its inherited cut");
		if (markedSeed && this.log.slice(inheritedEventCount + 1).some((event) => event.type === "session/end-seed" && event.data.inherited === true)) throw new Error("session inherited event count must identify the final inherited marker");
		this.inheritedEventCount = inheritedEventCount;
		this.firstLifecycleSeq = mode === "snapshot" && this.header.isSeeded ? inheritedEventCount : this.firstLiveSeq;
		if (seed !== void 0 && mode === "snapshot" && this.header.isSeeded && !markedSeed) this.append("session/end-seed", { inherited: true });
		else if (seed !== void 0 && !(mode === "snapshot" && this.header.isSeeded) && this.log.at(-1)?.type !== "session/end-seed") this.append("session/end-seed", {});
	}
	/** Cached immutable full snapshot of the private append-only log. */
	eventsSnapshot;
	/**
	* Return the immutable event stored at one exact sequence number.
	* @deprecated Existing logic may remain unmigrated for now, but new calls are prohibited.
	* See the [Agent Note](../../../../.agents/notes/implemented/architecture/2026-09-09-deprecate-synchronous-session-event-reads.md).
	* @param seq - event sequence number.
	* @returns the accepted event, or undefined when the log does not contain it.
	*/
	eventAt(seq) {
		return this.log[seq];
	}
	/**
	* Materialize an immutable snapshot of a half-open event sequence range.
	* A full current snapshot is reused until the next append; every previously
	* returned snapshot remains stable after later appends.
	* @deprecated Existing logic may remain unmigrated for now, but new calls are prohibited.
	* See the [Agent Note](../../../../.agents/notes/implemented/architecture/2026-09-09-deprecate-synchronous-session-event-reads.md).
	* @param fromSeq - non-negative inclusive sequence number; defaults to the log start.
	* @param toSeqExclusive - non-negative exclusive sequence number; defaults to the current end.
	* @returns a frozen array of the selected deeply frozen events.
	*/
	snapshotEvents(fromSeq = SessionLogOffset(0), toSeqExclusive = this.seq) {
		if (fromSeq === 0 && toSeqExclusive === this.log.length) {
			this.eventsSnapshot ??= Object.freeze([...this.log]);
			return this.eventsSnapshot;
		}
		return Object.freeze(this.log.slice(fromSeq, toSeqExclusive));
	}
	/**
	* Return this Session's events after its fork-inherited prefix.
	* @deprecated Existing logic may remain unmigrated for now, but new calls are prohibited.
	* See the [Agent Note](../../../../.agents/notes/implemented/architecture/2026-09-09-deprecate-synchronous-session-event-reads.md).
	* @returns a fresh array containing child-owned events in log order.
	*/
	ownEvents() {
		return this.snapshotEvents(this.inheritedEventCount);
	}
	/**
	* Whether one existing event position is outside the fork-inherited prefix.
	* @param seq - event position in this Session.
	* @returns true when the event belongs to this Session rather than its parent.
	*/
	isOwnSeq(seq) {
		return seq >= this.inheritedEventCount && seq < this.seq;
	}
	/** The next event's sequence number — always the log length (the `seq = log.length` contiguity contract). */
	get seq() {
		return SessionLogOffset(this.log.length);
	}
	/**
	* Append one typed event to the log and synchronously notify observers via
	* the store-owned, module-private publication hooks. The hot path never blocks
	* on I/O — persistence plugins buffer asynchronously. Once the event enters
	* the log, the append is committed: observer failures are logged and
	* contained per listener, so they do not change the return value or prevent
	* later listeners from observing the same accepted event.
	*
	* @param type - The event type (key of {@link SessionEventMap}).
	* @param data - The event payload; must be JSON-serializable.
	* @param opts - Surface metadata: `surfaceOp` controls how the event enters
	*   the ordered surface; `sourceEventSeqs` lists the seq numbers of earlier
	*   events this one derives from. REQUIRED for
	*   {@link SurfaceEventType} events (every message-producing event must
	*   declare how it joins the surface, the sole source of derived model
	*   history) and
	*   rejected by the compiler for non-surface types like `turn/start` or
	*   `assistant/attempt`. Assistant messages embed their exact provider
	*   stream and cannot cite top-level source events.
	* @returns the logged event — its assigned `seq`/`time` plus the SNAPSHOT of
	*   `data` that entered the log, so reading `event.data` back sees the logged
	*   value, never the caller's still-mutable input.
	* @throws if `data` or surface metadata is not losslessly JSON-serializable
	*   (BigInt, function, symbol, undefined, negative zero, non-finite number,
	*   circular reference, sparse array, or an exotic object such as
	*   Map/Set/Date/class instance), or when the candidate violates the
	*   request-header empty-field or tool-error consistency rules, or the
	*   canonical surface contract (marker shape and eligibility, unique
	*   earlier source-event references, positional replacement validity, and complete
	*   shadowed-node coverage). One iterative pass reads, validates, and
	*   copies each nested value once, so a stateful getter cannot supply one value
	*   to validation and another to storage. The event log is the durable source
	*   of truth, so a bad event fails at the append site rather than later during
	*   a backend flush. A synchronous internal dispatch validation failure or an
	*   append reentered while this acceptance/publication boundary is open also
	*   rejects before the log changes.
	*/
	append(type, data, ...opts) {
		const surfaceOpts = opts[0];
		const surfaceMetadata = {
			...surfaceOpts?.sourceEventSeqs === void 0 ? {} : { sourceEventSeqs: surfaceOpts.sourceEventSeqs },
			...surfaceOpts?.surfaceOp === void 0 ? {} : { surfaceOp: surfaceOpts.surfaceOp }
		};
		const dataSnapshot = snapshotJsonValue(data);
		if (dataSnapshot === void 0) throw new Error(`session event "${type}" carries non-JSON-serializable data`);
		const surfaceMetadataSnapshot = snapshotJsonValue(surfaceMetadata);
		if (surfaceMetadataSnapshot === void 0) throw new Error(`session event "${type}" carries non-JSON-serializable surface metadata`);
		const entry = attachments.get(this);
		if (entry?.appending) throw new Error("session append cannot reenter while another append is being published");
		const event = deepFreeze({
			type,
			seq: SessionSeq(this.log.length),
			time: Date.now(),
			data: dataSnapshot,
			...surfaceMetadataSnapshot
		});
		validateSessionEventData(event, `session event "${type}" at seq ${event.seq}`);
		this.surfaceManager.validateNext(event);
		if (entry !== void 0) entry.appending = true;
		try {
			let callbacks;
			const callbackArgs = [this, event];
			if (entry !== void 0) callbacks = collectSessionCallbacks(entry.emitCtx, [
				entry.carrier,
				"session/event",
				...callbackArgs
			]);
			this.log.push(event);
			this.eventsSnapshot = void 0;
			if (callbacks !== void 0 && entry !== void 0) invokeContainedSessionObservers(entry.emitCtx, "session/event", entry.id, callbackArgs, callbacks);
			return event;
		} finally {
			if (entry !== void 0) {
				entry.appending = false;
				if (entry.detachRequested && !entry.announcing) entry.detach();
			}
		}
	}
	/** Cached fold of the request-header events — see {@link requestHeader}. */
	headerFold;
	/** Log position (events consumed) the header fold has reached. */
	headerFoldSeq = 0;
	/**
	* The {@link EpochHeader} in force after the log's last header event — the
	* header the NEXT request will be compared against — or undefined before
	* the first `request/header` snapshot. The live, incrementally-maintained
	* form of `foldRequestHeader(session.snapshotEvents())`: each header event is folded
	* once, when first seen, so a per-step read costs O(new events).
	* @returns the folded header, or undefined when no header event exists yet.
	*/
	requestHeader() {
		if (this.headerFoldSeq < this.log.length) {
			this.headerFold = deepFreeze(foldRequestHeader(this.log.slice(this.headerFoldSeq), this.headerFold));
			this.headerFoldSeq = this.log.length;
		}
		return this.headerFold;
	}
	/** Cached fold of `request/context` events. */
	contextFold;
	contextFoldSeq = 0;
	/**
	* Return the latest resolved route metadata, or `undefined` before the first
	* `request/context` event. Each event is folded once.
	* @returns the latest immutable route metadata.
	*/
	requestContext() {
		if (this.contextFoldSeq < this.log.length) {
			for (const event of this.log.slice(this.contextFoldSeq)) if (event.type === "request/context") this.contextFold = deepFreeze({ ...event.data });
			this.contextFoldSeq = this.log.length;
		}
		return this.contextFold;
	}
	/** Cached historical tool definitions and updates for request projection. */
	toolHistoryProjection = new ToolHistoryProjection();
	/** Index of the next committed event not yet consumed by the tool-history fold. */
	toolHistorySeq = 0;
	/**
	* Fold unseen committed events into capability-independent tool history.
	* Initial access reconstructs inherited history; later reads consume only new events.
	* @returns an immutable snapshot for LLM request projection, including historical addition definitions.
	*/
	toolHistory() {
		for (const event of this.log.slice(this.toolHistorySeq)) this.toolHistoryProjection.apply(event);
		this.toolHistorySeq = this.log.length;
		return this.toolHistoryProjection.snapshot();
	}
	/** The derived-message cache: frozen projections, extended per unseen node. */
	derived = [];
	/** Surface position (nodes projected) the cache has reached. */
	derivedNodes = 0;
	/** {@link SurfaceManager.contentGeneration} the cache was built under. */
	derivedGeneration = 0;
	/**
	* Derive the LLM message history by walking the ordered sequences of
	* message-producing events maintained by `surfaceOp` markers. The
	* surface is the single source of derived history: every message-producing
	* append records its `surfaceOp`, so a raw event with no marker (a chunk, a
	* turn boundary) is correctly absent, and a compaction `replace` deletes the
	* shadowed nodes from the derivation. The projection rules are
	* {@link deriveEventMessage}, with logged message projections applied
	* without changing node membership or message identity.
	*
	* CACHED: pure tail growth costs O(new nodes); a replacement or message projection
	* ({@link SessionSurface.contentGeneration}) rebuilds. The returned array is
	* a fresh snapshot per call (later appends never grow an array a caller
	* already holds); the `Message` objects in it are SHARED and **deep-frozen**.
	* Unchanged content reuses frozen event data; projected blocks are frozen
	* derived copies. Consumers cannot mutate the log through either form.
	* @returns a fresh array of the shared, frozen derived history.
	*/
	deriveMessages() {
		const surface = this.surface;
		const nodes = surface.nodes;
		const generation = surface.contentGeneration;
		if (generation !== this.derivedGeneration) {
			this.derived = [];
			this.derivedNodes = 0;
			this.derivedGeneration = generation;
		}
		for (const seq of nodes.slice(this.derivedNodes)) {
			const msg = this.deriveEventMessage(this.log[seq]);
			if (msg) this.derived.push(msg);
		}
		this.derivedNodes = nodes.length;
		return [...this.derived];
	}
	/**
	* Project one event with all committed message projections applied.
	* The original durable event remains unchanged.
	* @param event - the event to project.
	* @returns the derived message, or null when the event produces none.
	*/
	deriveEventMessage(event) {
		return this.surfaceManager.deriveEventMessage(event);
	}
};
/** Typed error for session fork rejections. */
var SessionForkError = class extends Error {
	code;
	constructor(message, code) {
		super(message);
		this.code = code;
		this.name = "SessionForkError";
	}
};
/**
* In-memory session store (`ctx.sessions`).
*
* Persistence is intentionally not implemented here — the agent lifecycle
* attaches a session-log writer to each published session's write handle;
* a session published outside that lifecycle persists nothing.
*/
var SessionStore = class extends Service {
	store = /* @__PURE__ */ new Map();
	counter = 0;
	projections = [];
	/** Borrowed definitions for detached replay; contributions live until their registering fibers unload. */
	get messageProjections() {
		return this.projections;
	}
	/**
	* Register one event interpreter for live creation, restore, and fork.
	* Disposing the contribution makes sessions that used it refuse further derivation.
	* @param projection - pure definition owned by the event's plugin.
	* @returns the fiber-owned disposer.
	* @throws when another definition already owns this event type.
	*/
	registerMessageProjection(projection) {
		if (this.projections.some((item) => item.type === projection.type)) throw new Error(`session message projection "${projection.type}" is already registered`);
		return this.ctx.effect(() => {
			this.projections.push(projection);
			return () => {
				this.projections.splice(this.projections.indexOf(projection), 1);
			};
		}, "sessions.registerMessageProjection()");
	}
	constructor(ctx) {
		super(ctx, "sessions");
		ctx.inject(["typert"], (typeCtx) => {
			typeCtx.typert.lookups.register("session", {
				parameter: "session",
				wire: "sessionId",
				hostTypeSymbol: "@deepseek-ai/dsh-session#Session",
				wireTypeSymbol: "@deepseek-ai/dsh-session/types#SessionId",
				resolve: (sessionId) => this.get(sessionId)
			});
		});
	}
	/**
	* Create a session owned by the calling fiber: disposing that fiber stops
	* event notification and removes the session from the store. `options.seed`
	* populates the session with a copy of those events (replay/fork);
	* `options.meta` attaches creation metadata (validated absolute `cwd`, seed
	* and parent lineage, and delegation depth) as the immutable
	* {@link SessionHeader} (the store fills `version`/`id`/`createdAt`).
	*
	* For an agent whose session must be torn down IN ORDER with its loop (so the
	* loop's final events are published before the store attachment ends), do NOT use this
	* — fold the session lifecycle into the agent's own effect via
	* {@link prepare} + {@link enter} + {@link announce} (see
	* `dsh-agent-loop`'s creation transaction).
	*
	* @param id - the session id; omitted, the store mints `session-<n>`.
	* @param options - seed events and/or creation metadata for the header.
	* @returns the live session, already entered and announced.
	* @throws if a session with `id` already exists, metadata is not a plain
	*   lossless-JSON record with valid scalar fields, or `meta.cwd` is a
	*   non-absolute path (storage backends key directories off it).
	*/
	create(id, options) {
		const session = this.prepare(id, options);
		this.ctx.effect(function* () {
			yield this.enter(session);
			this.announce(session);
		}.bind(this), "sessions.create()");
		return session;
	}
	/**
	* Build a session WITHOUT entering it into the store — validate the id/cwd and
	* construct the {@link Session} (with its immutable {@link SessionHeader}).
	* Pairs with {@link enter} + {@link announce}: a caller that owns a composite
	* `ctx.effect` (the agent factory) folds the session lifecycle into that ONE
	* effect so a fiber unload tears the session + agent down as a single ORDERED
	* chain rather than as racing sibling effects — which would remove the publication hooks
	* before the driver's closing events commit, dropping them.
	*
	* @param id - the session id; omitted, the store mints `session-<n>`.
	* @param options - seed events and/or creation metadata for the header. With
	*   `eventState`, every seed event is either independently owned or any
	*   shared value is deeply frozen; {@link Session.fromRestore} validates and
	*   adopts those values without copying or freezing them.
	* @returns the constructed session, NOT yet in the store.
	* @throws if a session with `id` already exists, metadata is not a plain
	*   lossless-JSON record with valid scalar fields, or `meta.cwd` is a
	*   non-absolute path.
	*/
	prepare(id, options) {
		let sessionId;
		if (id === void 0) do
			sessionId = brandString(`session-${++this.counter}`);
		while (this.store.has(sessionId));
		else sessionId = brandString(id);
		if (this.store.has(sessionId)) throw new Error(`session "${sessionId}" already exists`);
		if (options !== void 0) {
			const { eventState } = options;
			switch (eventState) {
				case "detached":
				case "shared-frozen": return Session.fromRestore(sessionId, options.seed, options.meta, options.inheritedEventCount, eventState, this.projections);
				case void 0: break;
				/* v8 ignore next -- closed-union exhaustiveness guard */
				default: assertNever(eventState, "SessionStore.prepare event state");
			}
		}
		const seed = options?.seed;
		const meta = options?.meta;
		const header = {
			version: 4,
			id: sessionId,
			createdAt: meta?.createdAt ?? Date.now(),
			...meta?.cwd === void 0 ? {} : { cwd: meta.cwd },
			...meta?.parentSession === void 0 ? {} : { parentSession: meta.parentSession },
			isSeeded: meta?.isSeeded ?? false,
			...meta?.origin === void 0 ? {} : { origin: meta.origin },
			...meta?.delegationDepth === void 0 ? {} : { delegationDepth: meta.delegationDepth },
			...meta?.agentPreset === void 0 ? {} : { agentPreset: meta.agentPreset }
		};
		return Session.create(sessionId, seed, header, options?.inheritedEventCount, this.projections);
	}
	/**
	* Enter a {@link prepare}d session into the store: install the module-private
	* append publication hooks and add it to the store. Returns the DETACH
	* disposer (hooks + store removal). Does NOT emit `session/created` —
	* the caller yields this disposer inside its effect and THEN calls
	* {@link announce}, so a throwing `session/created` listener rolls the attach
	* back instead of leaking it.
	*
	* Re-checks the id for a duplicate: `prepare` and `enter` are public
	* cross-package primitives and a caller may interleave arbitrary work (or
	* another create) between them, so a stale prepared session must NOT overwrite
	* a live store entry of the same id — its detach disposer would later delete
	* the REAL session. The {@link create} convenience and the agent factory call
	* the two back-to-back so they never trip this, but the public API cannot
	* assume that.
	*
	* @param session - a {@link prepare}d session not yet in the store.
	* @returns the detach disposer (publication hooks + store removal). When called from
	*   a synchronous `session/created` listener, removal and disposal wait until
	*   that creation dispatch unwinds.
	* @throws if a session with this id is already in the store.
	*/
	enter(session) {
		const id = session.id;
		const carrier = scopeTarget(session, scopeOf(this.ctx));
		if (this.store.has(id)) throw new Error(`session "${id}" already exists`);
		if (attachments.has(session)) throw new Error(`session "${id}" is already attached to a store`);
		const entry = {
			id,
			session,
			carrier,
			emitCtx: this.ctx,
			announced: false,
			announcing: false,
			appending: false,
			detachRequested: false,
			detach: () => {
				this.detachEntered(entry);
			}
		};
		this.store.set(id, entry);
		attachments.set(session, entry);
		let entered = true;
		const detach = () => {
			if (!entered) return;
			entered = false;
			if (entry.announcing || entry.appending) {
				entry.detachRequested = true;
				return;
			}
			entry.detach();
		};
		return detach;
	}
	/** Remove one exact entered session and emit its paired disposal when announced. */
	detachEntered(entry) {
		entry.detachRequested = false;
		/* v8 ignore next -- enter() rejects replacement while this single-shot detach capability is live. */
		if (this.store.get(entry.id) !== entry) return;
		this.store.delete(entry.id);
		attachments.delete(entry.session);
		if (entry.announced) this.emitDisposed(entry);
	}
	/** Emit `session/created` exactly once for an {@link enter}ed session (with
	* the carrier {@link enter} captured). Separate from {@link enter} so the
	* caller can yield the detach disposer first (rollback safety — see
	* {@link enter}).
	* @param session - the entered session to announce to listeners.
	* @throws if the session is not live or its announcement already began,
	*   including a reentrant call from a creation listener. */
	announce(session) {
		const entry = this.liveEntryFor(session);
		if (entry.announced || entry.announcing) throw new Error(`session "${entry.id}" was already announced`);
		entry.announced = true;
		const callbackArgs = [session];
		entry.announcing = true;
		try {
			const callbacks = collectSessionCallbacks(this.ctx, [
				entry.carrier,
				"session/created",
				session
			]);
			for (const callback of callbacks) {
				const returned = callback(...callbackArgs);
				Promise.resolve(returned).catch((error) => {
					this.ctx.logger.warn(`session "${entry.id}": session/created listener rejected: ${String(error)}`);
				});
			}
		} finally {
			entry.announcing = false;
			if (entry.detachRequested && !entry.appending) entry.detach();
		}
	}
	/** Emit the paired teardown notification with per-listener containment. */
	emitDisposed(entry) {
		const callbackArgs = [entry.session];
		try {
			const callbacks = collectSessionCallbacks(this.ctx, [
				entry.carrier,
				"session/disposed",
				entry.session
			]);
			invokeContainedSessionObservers(this.ctx, "session/disposed", entry.id, callbackArgs, callbacks);
		} catch (error) {
			this.ctx.logger.warn(`session "${entry.id}": session/disposed dispatch threw: ${String(error)}`);
		}
	}
	/**
	* Dispatch the awaited `session/flush` durability checkpoint for `session`,
	* with the carrier captured at {@link enter}. THE flush entry point: the
	* store owns the carrier, so callers (the checkpoint policy's per-request
	* barrier, goal-round-driver's idle checkpoint, teardown drains, and consumers
	* that flush themselves before reading storage) must come through here
	* rather than dispatch a raw `ctx.parallel('session/flush', …)` — one owner,
	* one spelling, and the scoped-dispatch invariant can pin it.
	* @param session - the session whose buffered events must reach durable storage.
	* @returns whether at least one durability listener participated, after every
	*   listener has settled successfully.
	* @throws the first registered listener failure after every listener settles.
	*/
	async flush(session) {
		const { carrier } = this.liveEntryFor(session);
		const callbackArgs = [session];
		const callbacks = collectSessionCallbacks(this.ctx, [
			carrier,
			"session/flush",
			session
		]);
		const failure = (await Promise.allSettled(callbacks.map((callback) => {
			try {
				return callback(...callbackArgs);
			} catch (error) {
				return Promise.reject(error);
			}
		}))).find((result) => result.status === "rejected");
		if (failure !== void 0) throw failure.reason;
		return callbacks.length > 0;
	}
	/** Return the exact live entry; detached/prepared objects reject. */
	liveEntryFor(session) {
		const entry = attachments.get(session);
		if (entry === void 0 || this.store.get(entry.id) !== entry) throw new Error(`session "${session.id}" is not live in this store`);
		return entry;
	}
	/**
	* Look up a live session.
	* @param id - the session id to look up.
	* @returns the session, or undefined when no live session has that id.
	*/
	get(id) {
		return this.store.get(id)?.session;
	}
	/**
	* All live sessions, in creation order.
	* @returns a fresh array; mutating it does not affect the store.
	*/
	list() {
		return [...this.store.values()].map((entry) => entry.session);
	}
	/**
	* Create a live child session from an exact prefix of a live source.
	* `boundary` is an inclusive source event seq; omitted means the source's
	* current last event. An open tail receives synthetic tool results and
	* step/turn closers with the forked cause. Closed steps and turns remain
	* unchanged, including any failed tool calls already missing results.
	* `inheritedEventCount` counts only copied source events, excluding these closers.
	*
	* @param source - Live source session object or id.
	* @param boundary - Inclusive source event seq to fork through; omitted means
	*   the source's current last event, and omitted on an empty source forks an
	*   empty child.
	* @param childSessionId - Optional child session id; omitted delegates to
	*   `SessionStore`'s id policy.
	* @returns The created live child session.
	*/
	fork(source, boundary, childSessionId) {
		if (childSessionId !== void 0 && this.get(childSessionId) !== void 0) throw new SessionForkError(`session "${childSessionId}" already exists`, "SESSION_ALREADY_EXISTS");
		const liveSource = this._resolveForkSource(source);
		const events = liveSource.snapshotEvents();
		const resolved = this._forkBoundary(liveSource.id, events, boundary);
		const seed = resolved === void 0 ? [] : buildForkSeed(events, resolved);
		return this.create(childSessionId, {
			seed,
			inheritedEventCount: SessionLogOffset(resolved === void 0 ? 0 : resolved + 1),
			meta: {
				...liveSource.header.cwd !== void 0 ? { cwd: liveSource.header.cwd } : {},
				parentSession: liveSource.id,
				isSeeded: true
			}
		});
	}
	_forkBoundary(sessionId, events, requestedBoundary) {
		const lastEvent = events.at(-1);
		let boundary;
		if (requestedBoundary !== void 0) boundary = requestedBoundary;
		else {
			if (lastEvent === void 0) return void 0;
			boundary = lastEvent.seq;
		}
		if (!Number.isSafeInteger(boundary) || boundary < 0) throw new SessionForkError(`fork boundary for session "${sessionId}" must be a non-negative safe integer, got ${String(boundary)}`, "INVALID_BOUNDARY");
		if (boundary >= events.length) {
			const lastSeq = lastEvent?.seq;
			throw new SessionForkError(`fork boundary ${boundary} does not exist in session "${sessionId}" (last seq: ${lastSeq ?? "none"})`, "INVALID_BOUNDARY");
		}
		const boundaryEvent = events[boundary];
		if (boundaryEvent === void 0 || boundaryEvent.seq !== boundary) throw new SessionForkError(`fork boundary ${boundary} does not match a contiguous event seq in session "${sessionId}"`, "INVALID_BOUNDARY");
		return boundary;
	}
	_resolveForkSource(source) {
		if (typeof source === "string") {
			const session = this.get(source);
			if (session === void 0) throw new SessionForkError(`session "${source}" not found`, "SESSION_NOT_FOUND");
			return session;
		}
		const live = this.get(source.id);
		if (live === void 0) throw new SessionForkError(`session "${source.id}" not found`, "SESSION_NOT_FOUND");
		if (live !== source) throw new SessionForkError(`session "${source.id}" is not the live store instance`, "SESSION_NOT_LIVE");
		return source;
	}
};
//#endregion
export { KNOWN_SESSION_EVENT_TYPES, SESSION_FORMAT_VERSION, Session, SessionForkError, SessionId, SessionLogOffset, SessionPreparation, SessionSeq, SessionStore, SessionStore as default, TOOL_NOT_STARTED, TOOL_OUTCOME_UNKNOWN, ToolCallRecovery, adoptSessionEvent, buildForkSeed, canonicalHeader, decodeSeqRanges, deriveEventMessage, encodeSeqRanges, foldRequestHeader, foldSurface, headerEquals, interruptedTurnClosers, isAppendSurfaceEvent, isReplacementSurfaceEvent, isSurfaceEligibleType, isSurfaceEvent, snapshotSessionEvent };
