/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_client_ui_plugin_manager_pluginRegistryProbe_fastest_result$schema$value
const _deepseek_ai_dsh_client_ui_plugin_manager_pluginRegistryProbe_fastest_result$schema = () => (_deepseek_ai_dsh_client_ui_plugin_manager_pluginRegistryProbe_fastest_result$schema$value ??= z.union([z.literal(null), z.string()]))

export const TYPERT = {
  package: '@deepseek-ai/dsh-client-ui-plugin-manager',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-client-ui-plugin-manager#pluginRegistryProbe/fastest',
      service: 'pluginRegistryProbe',
      namespace: 'pluginRegistryProbe',
      method: 'fastest',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-client-ui-plugin-manager#pluginRegistryProbe/fastest:result',
        create: _deepseek_ai_dsh_client_ui_plugin_manager_pluginRegistryProbe_fastest_result$schema,
      },
      sourceLocation: {"file":"packages/client/ui-plugin-manager/src/index.ts","line":51,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Compares public registry responses on the Host; the Client owns the initial selection.",
        "summary": "Compares public registry responses on the Host; the Client owns the initial selection.",
        "tags": [],
        "jsDoc": "/** Compares public registry responses on the Host; the Client owns the initial selection. */",
        "key": "pluginRegistryProbe",
        "exportName": "default",
        "members": [
          {
            "kind": "method",
            "name": "fastest",
            "signature": "@Remote async fastest(): Promise<string | null>",
            "summary": "Race npm and npmmirror HTTPS ping responses through the Host's fetch proxy.",
            "jsDoc": "/**\n * Race npm and npmmirror HTTPS ping responses through the Host's fetch proxy.\n * Concurrent readers share a probe; a winner cancels and awaits the other request.\n * @returns the first registry with a successful response, or null when disabled or neither responds successfully; results are cached.\n * @throws rejects when the service has been unloaded.\n */"
          }
        ],
        "types": []
      }
    ],
    "events": [],
    "objects": []
  },
}
