/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_message_feedback_messageFeedback_delete_parameter_0$schema$value
const _deepseek_ai_dsh_message_feedback_messageFeedback_delete_parameter_0$schema = () => (_deepseek_ai_dsh_message_feedback_messageFeedback_delete_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'messageId': z.intersection(z.string(), z.unknown()).readonly(),
  'ifVersion': z.intersection(z.string(), z.unknown()).readonly(),
}))
let _deepseek_ai_dsh_message_feedback_messageFeedback_delete_result$schema$value
const _deepseek_ai_dsh_message_feedback_messageFeedback_delete_result$schema = () => (_deepseek_ai_dsh_message_feedback_messageFeedback_delete_result$schema$value ??= z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'absent': z.literal(true).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("session-not-found").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("version-conflict").readonly(),
  'current': z.union([z.literal(null), z.object({
  'messageId': z.intersection(z.string(), z.unknown()).readonly(),
  'rating': z.union([z.literal("positive"), z.literal("negative")]).readonly(),
  'note': z.string().readonly().optional(),
  'category': z.union([z.literal("other"), z.literal("task-result"), z.literal("instruction-following"), z.literal("product-interaction"), z.literal("service-stability"), z.literal("resource-cost"), z.literal("security-privacy-permission")]).readonly().optional(),
  'version': z.intersection(z.string(), z.unknown()).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})]).readonly(),
})]).readonly(),
})]))
let _deepseek_ai_dsh_message_feedback_messageFeedback_list_parameter_0$schema$value
const _deepseek_ai_dsh_message_feedback_messageFeedback_list_parameter_0$schema = () => (_deepseek_ai_dsh_message_feedback_messageFeedback_list_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}))
let _deepseek_ai_dsh_message_feedback_messageFeedback_list_result$schema$value
const _deepseek_ai_dsh_message_feedback_messageFeedback_list_result$schema = () => (_deepseek_ai_dsh_message_feedback_messageFeedback_list_result$schema$value ??= z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'messageId': z.intersection(z.string(), z.unknown()).readonly(),
  'rating': z.union([z.literal("positive"), z.literal("negative")]).readonly(),
  'note': z.string().readonly().optional(),
  'category': z.union([z.literal("other"), z.literal("task-result"), z.literal("instruction-following"), z.literal("product-interaction"), z.literal("service-stability"), z.literal("resource-cost"), z.literal("security-privacy-permission")]).readonly().optional(),
  'version': z.intersection(z.string(), z.unknown()).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.literal("session-not-found").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}).readonly(),
})]))
let _deepseek_ai_dsh_message_feedback_messageFeedback_put_parameter_0$schema$value
const _deepseek_ai_dsh_message_feedback_messageFeedback_put_parameter_0$schema = () => (_deepseek_ai_dsh_message_feedback_messageFeedback_put_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'messageId': z.intersection(z.string(), z.unknown()).readonly(),
  'rating': z.union([z.literal("positive"), z.literal("negative")]).readonly(),
  'note': z.string().readonly().optional(),
  'category': z.union([z.literal("other"), z.literal("task-result"), z.literal("instruction-following"), z.literal("product-interaction"), z.literal("service-stability"), z.literal("resource-cost"), z.literal("security-privacy-permission")]).readonly().optional(),
  'ifVersion': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
}))
let _deepseek_ai_dsh_message_feedback_messageFeedback_put_result$schema$value
const _deepseek_ai_dsh_message_feedback_messageFeedback_put_result$schema = () => (_deepseek_ai_dsh_message_feedback_messageFeedback_put_result$schema$value ??= z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'messageId': z.intersection(z.string(), z.unknown()).readonly(),
  'rating': z.union([z.literal("positive"), z.literal("negative")]).readonly(),
  'note': z.string().readonly().optional(),
  'category': z.union([z.literal("other"), z.literal("task-result"), z.literal("instruction-following"), z.literal("product-interaction"), z.literal("service-stability"), z.literal("resource-cost"), z.literal("security-privacy-permission")]).readonly().optional(),
  'version': z.intersection(z.string(), z.unknown()).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("session-not-found").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("target-not-found").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'messageId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("version-conflict").readonly(),
  'current': z.union([z.literal(null), z.object({
  'messageId': z.intersection(z.string(), z.unknown()).readonly(),
  'rating': z.union([z.literal("positive"), z.literal("negative")]).readonly(),
  'note': z.string().readonly().optional(),
  'category': z.union([z.literal("other"), z.literal("task-result"), z.literal("instruction-following"), z.literal("product-interaction"), z.literal("service-stability"), z.literal("resource-cost"), z.literal("security-privacy-permission")]).readonly().optional(),
  'version': z.intersection(z.string(), z.unknown()).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})]).readonly(),
}), z.object({
  'code': z.literal("note-blank").readonly(),
}), z.object({
  'code': z.literal("note-too-large").readonly(),
  'maxBytes': z.number().readonly(),
  'actualBytes': z.number().readonly(),
})]).readonly(),
})]))

export const TYPERT = {
  package: '@deepseek-ai/dsh-message-feedback',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-message-feedback#messageFeedback/delete',
      service: 'messageFeedback',
      namespace: 'messageFeedback',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-message-feedback/types#MessageFeedbackDeleteRequest',
            create: _deepseek_ai_dsh_message_feedback_messageFeedback_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-message-feedback/types#MessageFeedbackDeleteResult',
        create: _deepseek_ai_dsh_message_feedback_messageFeedback_delete_result$schema,
      },
      sourceLocation: {"file":"packages/feedback/message-feedback/src/index.ts","line":207,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-message-feedback#messageFeedback/list',
      service: 'messageFeedback',
      namespace: 'messageFeedback',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-message-feedback/types#MessageFeedbackListRequest',
            create: _deepseek_ai_dsh_message_feedback_messageFeedback_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-message-feedback/types#MessageFeedbackListResult',
        create: _deepseek_ai_dsh_message_feedback_messageFeedback_list_result$schema,
      },
      sourceLocation: {"file":"packages/feedback/message-feedback/src/index.ts","line":155,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-message-feedback#messageFeedback/put',
      service: 'messageFeedback',
      namespace: 'messageFeedback',
      method: 'put',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-message-feedback/types#MessageFeedbackPutRequest',
            create: _deepseek_ai_dsh_message_feedback_messageFeedback_put_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-message-feedback/types#MessageFeedbackPutResult',
        create: _deepseek_ai_dsh_message_feedback_messageFeedback_put_result$schema,
      },
      sourceLocation: {"file":"packages/feedback/message-feedback/src/index.ts","line":167,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Session-log service; cold operations never construct a Session or Agent.",
        "summary": "Session-log service; cold operations never construct a Session or Agent.",
        "tags": [],
        "jsDoc": "/** Session-log service; cold operations never construct a Session or Agent. */",
        "key": "messageFeedback",
        "exportName": "MessageFeedbackService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') list(request: MessageFeedbackListRequest): Promise<MessageFeedbackListResult>",
            "summary": "Read current feedback from the canonical log.",
            "jsDoc": "/**\n * Read current feedback from the canonical log.\n * @param request - Session to inspect.\n * @returns immutable items or a definite persistence miss.\n */"
          },
          {
            "kind": "method",
            "name": "put",
            "signature": "@Remote('put') put(request: MessageFeedbackPutRequest): Promise<MessageFeedbackPutResult>",
            "summary": "Create or replace feedback after checking its current version.",
            "jsDoc": "/**\n * Create or replace feedback after checking its current version.\n * Matching no-ops retain the version and append no event.\n * @param request - Target, desired value, and observed item version.\n * @returns the durable item or an explicit business failure.\n */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote('delete') delete(request: MessageFeedbackDeleteRequest): Promise<MessageFeedbackDeleteResult>",
            "summary": "Delete one item after checking its version; absence succeeds without an event.",
            "jsDoc": "/**\n * Delete one item after checking its version; absence succeeds without an event.\n * @param request - Session, message, and observed item version.\n * @returns the stable absent postcondition or an explicit failure.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "FeedbackCategory",
            "declaration": "export type FeedbackCategory = 'task-result' | 'instruction-following' | 'product-interaction' | 'service-stability' | 'resource-cost' | 'security-privacy-permission' | 'other';"
          },
          {
            "name": "MessageFeedbackDeleteRequest",
            "declaration": "export interface MessageFeedbackDeleteRequest {\n    readonly sessionId: SessionId;\n    readonly messageId: MessageId;\n    readonly ifVersion: MessageFeedbackVersion;\n}"
          },
          {
            "name": "MessageFeedbackDeleteResult",
            "declaration": "export type MessageFeedbackDeleteResult = MessageFeedbackSuccess<MessageFeedbackDeleteValue> | MessageFeedbackRejected<MessageFeedbackSessionNotFound | MessageFeedbackVersionConflict>;"
          },
          {
            "name": "MessageFeedbackDeleteValue",
            "declaration": "export interface MessageFeedbackDeleteValue {\n    readonly absent: true;\n}"
          },
          {
            "name": "MessageFeedbackFailure",
            "declaration": "export type MessageFeedbackFailure = MessageFeedbackSessionNotFound | MessageFeedbackTargetNotFound | MessageFeedbackVersionConflict | MessageFeedbackNoteBlank | MessageFeedbackNoteTooLarge;"
          },
          {
            "name": "MessageFeedbackItem",
            "declaration": "export interface MessageFeedbackItem {\n    readonly messageId: MessageId;\n    readonly rating: MessageFeedbackRating;\n    readonly note?: string;\n    readonly category?: FeedbackCategory;\n    readonly version: MessageFeedbackVersion;\n    readonly createdAt: number;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "MessageFeedbackListRequest",
            "declaration": "export interface MessageFeedbackListRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "MessageFeedbackListResult",
            "declaration": "export type MessageFeedbackListResult = MessageFeedbackSuccess<MessageFeedbackListValue> | MessageFeedbackRejected<MessageFeedbackSessionNotFound>;"
          },
          {
            "name": "MessageFeedbackListValue",
            "declaration": "export interface MessageFeedbackListValue {\n    readonly items: readonly MessageFeedbackItem[];\n}"
          },
          {
            "name": "MessageFeedbackNoteBlank",
            "declaration": "export interface MessageFeedbackNoteBlank {\n    readonly code: 'note-blank';\n}"
          },
          {
            "name": "MessageFeedbackNoteTooLarge",
            "declaration": "export interface MessageFeedbackNoteTooLarge {\n    readonly code: 'note-too-large';\n    readonly maxBytes: number;\n    readonly actualBytes: number;\n}"
          },
          {
            "name": "MessageFeedbackPutRequest",
            "declaration": "export interface MessageFeedbackPutRequest {\n    readonly sessionId: SessionId;\n    readonly messageId: MessageId;\n    readonly rating: MessageFeedbackRating;\n    readonly note?: string;\n    readonly category?: FeedbackCategory;\n    readonly ifVersion: MessageFeedbackVersion | null;\n}"
          },
          {
            "name": "MessageFeedbackPutResult",
            "declaration": "export type MessageFeedbackPutResult = MessageFeedbackSuccess<MessageFeedbackItem> | MessageFeedbackRejected<MessageFeedbackSessionNotFound | MessageFeedbackTargetNotFound | MessageFeedbackVersionConflict | MessageFeedbackNoteBlank | MessageFeedbackNoteTooLarge>;"
          },
          {
            "name": "MessageFeedbackRating",
            "declaration": "export type MessageFeedbackRating = 'positive' | 'negative';"
          },
          {
            "name": "MessageFeedbackRejected",
            "declaration": "export interface MessageFeedbackRejected<E extends MessageFeedbackFailure> {\n    readonly ok: false;\n    readonly error: E;\n}"
          },
          {
            "name": "MessageFeedbackSessionNotFound",
            "declaration": "export interface MessageFeedbackSessionNotFound {\n    readonly code: 'session-not-found';\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "MessageFeedbackSuccess",
            "declaration": "export interface MessageFeedbackSuccess<T> {\n    readonly ok: true;\n    readonly value: T;\n}"
          },
          {
            "name": "MessageFeedbackTargetNotFound",
            "declaration": "export interface MessageFeedbackTargetNotFound {\n    readonly code: 'target-not-found';\n    readonly sessionId: SessionId;\n    readonly messageId: MessageId;\n}"
          },
          {
            "name": "MessageFeedbackVersion",
            "declaration": "export type MessageFeedbackVersion = Branded<'MessageFeedbackVersion'>;"
          },
          {
            "name": "MessageFeedbackVersionConflict",
            "declaration": "export interface MessageFeedbackVersionConflict {\n    readonly code: 'version-conflict';\n    readonly current: MessageFeedbackItem | null;\n}"
          },
          {
            "name": "MessageId",
            "declaration": "export type MessageId = Branded<'MessageId'>;"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "Observe a durable cold feedback mutation without publishing a live Session. Observers run before write ownership is released and must not await another message-feedback operation for this Session. The payload is borrowed read-only; deep-clone it before transferring ownership (for example, to Session.fromRestore).",
        "summary": "Observe a durable cold feedback mutation without publishing a live Session.",
        "tags": [
          {
            "name": "param",
            "argument": "inspection",
            "comment": "- committed canonical prefix, including the feedback as its last event.",
            "text": "@param inspection - committed canonical prefix, including the feedback as its last event.\n     *"
          },
          {
            "name": "mode",
            "comment": "parallel",
            "text": "@mode parallel"
          }
        ],
        "jsDoc": "/**\n * Observe a durable cold feedback mutation without publishing a live Session.\n * Observers run before write ownership is released and must not await\n * another message-feedback operation for this Session. The payload is borrowed\n * read-only; deep-clone it before transferring ownership (for example, to Session.fromRestore).\n * @param inspection - committed canonical prefix, including the feedback as its last event.\n * @mode parallel\n */",
        "name": "feedback/committed",
        "mode": "parallel",
        "signature": "'feedback/committed'(inspection: SessionInspection): void"
      }
    ],
    "objects": []
  },
}
